
import hashlib
import re
from datetime import datetime
from html import escape
from typing import Any, Dict, List, Tuple

import pandas as pd
import streamlit as st

try:
    import gspread
    from google.oauth2.service_account import Credentials
except Exception:
    gspread = None
    Credentials = None


st.set_page_config(
    page_title="Brand For The Customer",
    page_icon="💗",
    layout="wide",
    initial_sidebar_state="expanded",
)

SPREADSHEET_ID = "13p7C3RIhUZ0yfIcRFbSbfI6YY-P8Lmyn1AWbbQ9K9I8"
SPREADSHEET_URL = f"https://docs.google.com/spreadsheets/d/{SPREADSHEET_ID}/edit"

# Keep source streams and expected columns unchanged.
SHEET_SOURCES = [
    {
        "brand": "Social With Rocki",
        "sheet_name": "Sheet1",
        "gid": "213898480",
        "description": "General Social With Rocki content generated by the first append stream.",
        "expected_columns": [
            "Blog", "Newsletter", "Podcast", "Pinterest", "Facebook", "X", "Linkedin", "Tiktok", "IG", "Blog (AI Agent)"
        ],
    },
    {
        "brand": "Cosmetology With Rocki",
        "sheet_name": "rocki_cosmetology_7_day_demo_content",
        "gid": "835739923",
        "description": "Rocki cosmetology content generated by the second append stream.",
        "expected_columns": [
            "Research Strategy", "Blog", "Newsletter", "Podcast", "Pinterest", "Facebook", "X", "Linkedin", "Tiktok", "IG"
        ],
    },
]

# Keep source-facing columns unchanged.
CHANNEL_COLUMNS = [
    "Research Strategy", "Blog", "Blog (AI Agent)", "Newsletter", "Podcast", "Pinterest", "Facebook", "X", "Linkedin", "Tiktok", "IG"
]

DISPLAY_NAMES = {
    "Research Strategy": "Research Strategy",
    "Blog": "Blog",
    "Blog (AI Agent)": "AI Agent Blog",
    "Newsletter": "Newsletter",
    "Podcast": "Podcast",
    "Pinterest": "Pinterest",
    "Facebook": "Facebook",
    "X": "X / Twitter",
    "Linkedin": "LinkedIn",
    "Tiktok": "TikTok",
    "IG": "Instagram",
}

PLATFORM_ICONS = {
    "Research Strategy": "🧠",
    "Blog": "📝",
    "Blog (AI Agent)": "🤖",
    "Newsletter": "💌",
    "Podcast": "🎙️",
    "Pinterest": "📌",
    "Facebook": "👥",
    "X": "⚡",
    "Linkedin": "💼",
    "Tiktok": "🎬",
    "IG": "📸",
}

PAGES = [
    "Dashboard",
    "Customer Brand",
    "Analytics",
    "Trend Finder",
    "Content Library",
    "Content Calendar",
    "CRUD Studio",
    "Export Center",
    "Source Health",
]

BRAND_STRATEGY = {
    "Social With Rocki": {
        "tagline": "Marketing, visibility, content systems, brand authority, and offer-led growth for beauty entrepreneurs.",
        "audience": "Beauty entrepreneurs, creators, salon owners, coaches, service providers, and future stylists building visibility.",
        "promise": "Turn content into trust, trust into community, and community into booked calls, subscribers, referrals, and paid offers.",
        "pillars": ["AI Content Systems", "Search-First Social", "Creator Brand Authority", "Client Proof Content", "Newsletter + Community", "Social Commerce", "Beauty Business Marketing"],
        "offers": ["7-Day Beauty Content Batch Kit", "Search-First Caption Bank", "Beauty Brand Audit", "Salon FAQ + AEO Pack", "LinkedIn Authority Pack", "Content Calendar Setup"],
    },
    "Cosmetology With Rocki": {
        "tagline": "Beauty school diary, cosmetology student survival, salon business lessons, and confidence-building content.",
        "audience": "Cosmetology students, future hairstylists, beauty school beginners, student stylists, and future salon owners.",
        "promise": "Help students survive school, document the journey, understand the business side, and build client-attraction confidence before graduation.",
        "pillars": ["Beauty School Survival", "Student Diary Series", "Marketing Meets Cosmetology", "Business Behind The Chair", "State Board Prep", "Client Experience", "Hair + Scalp Wellness"],
        "offers": ["Beauty School Starter Checklist", "Cosmetology Kit Audit Sheet", "State Board Study Planner", "Student Stylist Content Kit", "Salon Career Path Planner"],
    },
}

STATUS_ORDER = ["Idea", "Draft", "Needs Review", "Ready", "Scheduled", "Published", "Archived"]

THEME = """
<style>
@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700;900&family=Poppins:wght@300;400;500;600;700;800&display=swap');
:root{
  --bg:#fff7fb;
  --ink:#24151f;
  --muted:#765a6d;
  --pink:#e11d74;
  --purple:#8b5cf6;
  --teal:#14b8a6;
  --cream:#fffaf2;
  --gold:#f59e0b;
  --green:#0f766e;
  --line:rgba(225,29,116,.16);
  --shadow:0 18px 48px rgba(120,30,85,.12);
}
html, body, [data-testid="stAppViewContainer"]{
  background:
    radial-gradient(circle at 8% 0%,rgba(225,29,116,.18),transparent 27%),
    radial-gradient(circle at 90% 7%,rgba(139,92,246,.17),transparent 30%),
    linear-gradient(180deg,#fff7fb 0%,#fffaf2 52%,#fff7fb 100%)!important;
  font-family:'Poppins',sans-serif!important;
  color:var(--ink)!important;
}
[data-testid="stMain"]{background:transparent!important}
[data-testid="stSidebar"]{
  background:linear-gradient(180deg,rgba(255,255,255,.97),rgba(255,239,247,.98))!important;
  border-right:1px solid var(--line)!important;
  box-shadow:8px 0 36px rgba(225,29,116,.07)
}
[data-testid="stSidebar"] *{color:var(--ink)!important}
header,footer,#MainMenu,[data-testid="stToolbar"],[data-testid="stDecoration"],[data-testid="stStatusWidget"],[data-testid="stHeaderActionElements"]{
  display:none!important;visibility:hidden!important;height:0!important
}
div.block-container{padding-top:1.25rem!important;padding-bottom:2rem!important;max-width:1600px!important}
h1,h2,h3{font-family:'Playfair Display',serif!important;letter-spacing:-.03em}
h1{font-size:clamp(2.1rem,4vw,4.9rem)!important;line-height:.95!important;color:var(--ink)!important}
h2{color:#3a1630!important}
h3{color:var(--pink)!important}
[data-testid="stMetric"]{
  background:rgba(255,255,255,.78)!important;
  border:1px solid var(--line)!important;
  border-radius:24px!important;
  padding:18px 20px!important;
  box-shadow:var(--shadow)!important
}
[data-testid="stMetricValue"]{color:var(--pink)!important;font-family:'Playfair Display',serif!important;font-size:2.2rem!important}
[data-testid="stMetricLabel"]{color:var(--muted)!important;font-weight:800!important}
.stButton>button,.stDownloadButton>button,button[kind="primary"]{
  background:linear-gradient(135deg,var(--pink),var(--purple))!important;
  color:#fff!important;
  border:0!important;
  border-radius:999px!important;
  font-weight:800!important;
  padding:.68rem 1.2rem!important;
  box-shadow:0 10px 28px rgba(225,29,116,.22)!important
}
.stButton>button:hover,.stDownloadButton>button:hover{
  filter:brightness(1.02);
  transform:translateY(-1px);
}
.stTextInput input,.stTextArea textarea,[data-baseweb="select"]>div{
  background:rgba(255,255,255,.9)!important;
  border:1px solid rgba(225,29,116,.18)!important;
  border-radius:16px!important;
  color:var(--ink)!important
}
.hero-card,.glass-card,.mini-card,.content-card,.action-card,.kpi-card{
  border-radius:28px;
  border:1px solid var(--line)
}
.hero-card{
  position:relative;
  overflow:hidden;
  background:
    radial-gradient(circle at 88% 12%,rgba(20,184,166,.19),transparent 21%),
    radial-gradient(circle at 10% 8%,rgba(251,113,133,.24),transparent 24%),
    linear-gradient(135deg,rgba(255,255,255,.93),rgba(255,232,243,.84));
  padding:clamp(24px,4vw,48px);
  margin-bottom:18px;
  box-shadow:var(--shadow)
}
.glass-card,.mini-card,.content-card,.action-card,.kpi-card{
  background:rgba(255,255,255,.78);
  box-shadow:var(--shadow);
  backdrop-filter:blur(14px)
}
.glass-card{padding:24px;margin-bottom:18px}
.mini-card{padding:18px;margin-bottom:14px}
.content-card{padding:22px;margin-bottom:18px}
.action-card{padding:18px 20px;margin-bottom:14px}
.kpi-card{padding:18px 18px;margin-bottom:14px;min-height:144px}
.login-shell{
  max-width:1050px;
  margin:3rem auto 0;
  padding:1px;
  background:linear-gradient(135deg,rgba(225,29,116,.35),rgba(139,92,246,.26),rgba(20,184,166,.22));
  box-shadow:var(--shadow);
  border-radius:28px
}
.login-card{
  background:radial-gradient(circle at top right,rgba(225,29,116,.18),transparent 30%),linear-gradient(180deg,#fff,#fff0f7);
  padding:34px;
  border-radius:28px
}
.login-title{
  font-family:'Playfair Display',serif;
  font-size:clamp(2.5rem,6vw,5.3rem);
  font-weight:900;
  line-height:.92;
  margin:8px 0 14px;
  color:var(--ink)
}
.eyebrow{color:var(--pink);font-size:.72rem;font-weight:900;letter-spacing:.16em;text-transform:uppercase}
.muted{color:var(--muted);font-size:.93rem;line-height:1.65}
.content-title{color:var(--ink);font-size:1.08rem;font-weight:900;margin:6px 0 10px}
.content-copy{color:#3d2333;line-height:1.78;font-size:.93rem;white-space:pre-wrap;word-break:break-word}
.trend-copy{
  color:#7b365e;
  line-height:1.66;
  font-size:.86rem;
  white-space:pre-wrap;
  word-break:break-word;
  border-left:3px solid rgba(225,29,116,.32);
  padding-left:12px;
  margin:10px 0 14px
}
.pill{
  display:inline-block;
  border-radius:999px;
  padding:6px 11px;
  margin:4px 6px 4px 0;
  background:rgba(225,29,116,.08);
  border:1px solid rgba(225,29,116,.16);
  color:#a41454;
  font-size:.76rem;
  font-weight:900
}
.pill.green{background:rgba(20,184,166,.12);border-color:rgba(20,184,166,.22);color:#0f766e}
.pill.purple{background:rgba(139,92,246,.12);border-color:rgba(139,92,246,.2);color:#5b2fc7}
.pill.gold{background:rgba(245,158,11,.12);border-color:rgba(245,158,11,.25);color:#92400e}
.card-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px;margin:12px 0 20px}
.platform-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:16px;margin:12px 0 20px}
.action-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px;margin:12px 0 18px}
.big-number{font-family:'Playfair Display',serif;font-size:2.25rem;font-weight:900;color:var(--pink);line-height:1}
.check-list{margin:0;padding-left:1.1rem}.check-list li{margin-bottom:.55rem;color:#48283b;line-height:1.6}
.progress-wrap{width:100%;height:10px;border-radius:999px;background:#f6d9e8;overflow:hidden;margin-top:10px}
.progress-fill{height:100%;border-radius:999px;background:linear-gradient(90deg,var(--pink),var(--purple),var(--teal))}
.brand-band{height:8px;border-radius:999px;margin-bottom:12px;background:linear-gradient(90deg,var(--pink),var(--purple),var(--teal))}
.source-ok{color:#0f766e;font-weight:900}.source-bad{color:#b91c1c;font-weight:900}
.nav-chip{
  display:block;
  width:100%;
  text-align:center;
  text-decoration:none;
  border-radius:18px;
  padding:12px 14px;
  font-size:.85rem;
  font-weight:900;
  color:#a41454;
  background:rgba(255,255,255,.72);
  border:1px solid rgba(225,29,116,.14);
  margin-bottom:8px;
}
.status-dot{
  width:10px;height:10px;border-radius:99px;display:inline-block;margin-right:8px;background:var(--teal)
}
@media(max-width:760px){
  div.block-container{padding-left:1rem!important;padding-right:1rem!important}
  .hero-card,.glass-card,.content-card{border-radius:22px;padding:20px}
  .platform-grid,.card-grid,.action-grid{grid-template-columns:1fr}
  [data-testid="stMetric"]{padding:14px!important}
}
</style>
"""
st.markdown(THEME, unsafe_allow_html=True)


def safe_html(value: Any) -> str:
    return escape(str(value or ""))


def _hash_password(password: str) -> str:
    return hashlib.sha256(password.encode("utf-8")).hexdigest()


def _init_state() -> None:
    defaults = {
        "auth_ok": False,
        "auth_user": None,
        "auth_name": None,
        "auth_role": None,
        "page": "Dashboard",
        "customer_drafts": [],
    }
    for key, value in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = value


USERS = {
    "rocki": {"name": "Rocki", "role": "Customer Brand Admin", "password_hash": _hash_password("rocki2026")},
    "admin": {"name": "Admin", "role": "Customer Brand Admin", "password_hash": _hash_password("rocki2026")},
}


def _check_login(username: str, password: str) -> bool:
    record = USERS.get((username or "").strip().lower())
    return bool(record and record["password_hash"] == _hash_password(password or ""))


def _sign_in(username: str) -> None:
    record = USERS.get(username.strip().lower(), USERS["rocki"])
    st.session_state.auth_ok = True
    st.session_state.auth_user = username.strip().lower()
    st.session_state.auth_name = record["name"]
    st.session_state.auth_role = record["role"]


def _sign_out() -> None:
    for key in ["auth_ok", "auth_user", "auth_name", "auth_role"]:
        st.session_state[key] = False if key == "auth_ok" else None
    st.rerun()


def goto_page(page: str) -> None:
    if page in PAGES:
        st.session_state.page = page
        st.rerun()


def google_csv_url(gid: str) -> str:
    return f"https://docs.google.com/spreadsheets/d/{SPREADSHEET_ID}/export?format=csv&gid={gid}"


def has_service_account() -> bool:
    try:
        return bool(st.secrets.get("gcp_service_account")) and gspread is not None and Credentials is not None
    except Exception:
        return False


def read_private_sheet(gid: str) -> pd.DataFrame:
    scopes = ["https://www.googleapis.com/auth/spreadsheets.readonly"]
    creds = Credentials.from_service_account_info(dict(st.secrets["gcp_service_account"]), scopes=scopes)
    client = gspread.authorize(creds)
    workbook = client.open_by_key(SPREADSHEET_ID)
    worksheet = workbook.get_worksheet_by_id(int(gid))
    values = worksheet.get_all_values()
    if not values:
        return pd.DataFrame()
    headers = values[0]
    return pd.DataFrame(values[1:], columns=headers)


@st.cache_data(ttl=120, show_spinner=False)
def read_public_sheet(gid: str) -> pd.DataFrame:
    return pd.read_csv(google_csv_url(gid))


def first_line(value: Any, max_chars: int = 95) -> str:
    text = re.sub(r"\s+", " ", str(value or "")).strip()
    if not text:
        return ""
    line = text.split(".")[0].strip() or text
    return line[:max_chars].rstrip() + ("…" if len(line) > max_chars else "")


def extract_hashtags(text: Any) -> List[str]:
    return sorted(set(re.findall(r"#[A-Za-z0-9_]+", str(text or ""))))


def extract_mentions(text: Any) -> List[str]:
    return sorted(set(re.findall(r"@[A-Za-z0-9_]+", str(text or ""))))


def count_words(text: Any) -> int:
    return len(re.findall(r"\b\w+\b", str(text or "")))


def count_sentences(text: Any) -> int:
    return len([s for s in re.split(r"[.!?]+", str(text or "")) if s.strip()])


def count_cta_terms(text: Any) -> int:
    terms = ["comment", "dm", "book", "download", "join", "save", "share", "click", "register", "apply", "subscribe", "reply", "follow"]
    lower = str(text or "").lower()
    return sum(1 for term in terms if term in lower)


def count_hook_terms(text: Any) -> int:
    terms = ["how", "why", "stop", "start", "secret", "mistake", "before", "after", "checklist", "guide", "tips", "truth"]
    lower = str(text or "").lower()
    return sum(1 for term in terms if term in lower)


def content_stage(row: pd.Series) -> str:
    score = int(row.get("Opportunity Score", 0) or 0)
    pieces = int(row.get("Content Pieces", 0) or 0)
    words = int(row.get("Total Words", 0) or 0)
    if score >= 8 and pieces >= 7:
        return "Ready"
    if score >= 7 and words >= 900:
        return "Needs Review"
    if pieces >= 4:
        return "Draft"
    return "Idea"


def score_text(row: pd.Series) -> int:
    blob = " ".join(str(row.get(c, "")) for c in CHANNEL_COLUMNS)
    filled = sum(1 for c in CHANNEL_COLUMNS if str(row.get(c, "")).strip())
    keyword_bonus = sum(
        1
        for k in [
            "client", "marketing", "student", "business", "school", "content", "brand", "confidence",
            "search", "offer", "beauty", "cosmetology", "book", "download", "checklist", "save",
        ]
        if k in blob.lower()
    )
    hook_bonus = min(1, count_hook_terms(blob) // 3)
    cta_bonus = min(1, count_cta_terms(blob) // 3)
    hashtag_bonus = min(1, len(extract_hashtags(blob)) // 3)
    return min(10, 2 + min(4, filled // 2) + min(2, len(blob) // 1600) + min(1, keyword_bonus // 4) + hook_bonus + cta_bonus + hashtag_bonus)


def infer_primary_topic(row: pd.Series) -> str:
    for col in ["Trend", "Topic", "Title", "Research Strategy", "Blog", "Blog (AI Agent)", "IG", "Tiktok", "Linkedin", "Facebook"]:
        candidate = str(row.get(col, "")).strip()
        if candidate:
            return first_line(candidate)
    return "Customer content row"


def infer_pillar(brand: str, topic: str) -> str:
    lower = topic.lower()
    if brand == "Social With Rocki":
        if "ai" in lower:
            return "AI Content Systems"
        if "search" in lower or "seo" in lower or "aeo" in lower:
            return "Search-First Social"
        if "client" in lower or "proof" in lower:
            return "Client Proof Content"
        if "newsletter" in lower or "community" in lower:
            return "Newsletter + Community"
        if "commerce" in lower or "shop" in lower:
            return "Social Commerce"
        return "Beauty Business Marketing"
    if "state board" in lower or "exam" in lower:
        return "State Board Prep"
    if "student" in lower or "school" in lower or "kit" in lower:
        return "Beauty School Survival"
    if "client" in lower or "consult" in lower:
        return "Client Experience"
    if "business" in lower or "salon" in lower:
        return "Business Behind The Chair"
    if "scalp" in lower or "hair" in lower:
        return "Hair + Scalp Wellness"
    return "Student Diary Series"


def normalize_sheet(df: pd.DataFrame, source: Dict[str, str]) -> pd.DataFrame:
    frame = df.copy()
    frame.columns = [str(c).strip() for c in frame.columns]

    for col in CHANNEL_COLUMNS:
        if col not in frame.columns:
            frame[col] = ""
    for col in source["expected_columns"]:
        if col not in frame.columns:
            frame[col] = ""

    if "Brand" not in frame.columns:
        frame["Brand"] = source["brand"]
    frame["Brand"] = frame["Brand"].fillna("").replace("", source["brand"])

    frame = frame.fillna("").astype(str)
    frame["Source Sheet"] = source["sheet_name"]
    frame["Source GID"] = source["gid"]
    frame["Source URL"] = google_csv_url(source["gid"])
    frame["Source Row"] = range(2, len(frame) + 2)
    frame["Trend"] = frame.apply(infer_primary_topic, axis=1)
    if "Pillar" not in frame.columns:
        frame["Pillar"] = ""
    frame["Pillar"] = frame.apply(
        lambda r: r.get("Pillar") or infer_pillar(str(r.get("Brand", source["brand"])), str(r.get("Trend", ""))),
        axis=1,
    )
    frame["Hook"] = frame.apply(
        lambda r: first_line(r.get("IG") or r.get("Tiktok") or r.get("Linkedin") or r.get("Blog") or r.get("Research Strategy")),
        axis=1,
    )
    frame["Search Intent"] = frame.apply(lambda r: "Customer content planning and repurposing", axis=1)
    frame["Target Audience"] = frame["Brand"].map(lambda b: BRAND_STRATEGY.get(b, BRAND_STRATEGY[source["brand"]])["audience"])
    frame["CTA"] = frame.apply(lambda r: "Copy, repurpose, schedule, or turn into a customer offer.", axis=1)
    frame["Offer"] = frame["Brand"].map(lambda b: BRAND_STRATEGY.get(b, BRAND_STRATEGY[source["brand"]])["offers"][0])
    frame["Content Pieces"] = frame[CHANNEL_COLUMNS].apply(lambda r: int(r.astype(str).str.strip().ne("").sum()), axis=1)
    frame["Total Words"] = frame[CHANNEL_COLUMNS].apply(lambda r: sum(count_words(v) for v in r), axis=1)
    frame["Total Characters"] = frame[CHANNEL_COLUMNS].apply(lambda r: sum(len(str(v)) for v in r), axis=1)
    frame["Hashtag Count"] = frame[CHANNEL_COLUMNS].apply(lambda r: sum(len(extract_hashtags(v)) for v in r), axis=1)
    frame["Mention Count"] = frame[CHANNEL_COLUMNS].apply(lambda r: sum(len(extract_mentions(v)) for v in r), axis=1)
    frame["CTA Signals"] = frame[CHANNEL_COLUMNS].apply(lambda r: sum(count_cta_terms(v) for v in r), axis=1)
    frame["Hook Signals"] = frame[CHANNEL_COLUMNS].apply(lambda r: sum(count_hook_terms(v) for v in r), axis=1)
    frame["Opportunity Score"] = frame.apply(score_text, axis=1)
    frame["Readiness"] = frame.apply(content_stage, axis=1)
    frame["Completeness %"] = frame["Content Pieces"].apply(lambda x: round((int(x) / max(1, len(CHANNEL_COLUMNS))) * 100, 1))
    frame["Repurpose Score"] = frame.apply(
        lambda r: min(100, int(r["Completeness %"]) + min(20, int(r["CTA Signals"]) * 2) + min(20, int(r["Hook Signals"]) * 2)),
        axis=1,
    )
    frame["Last Refresh"] = datetime.now().strftime("%Y-%m-%d %I:%M %p")
    return frame


def load_content_streams() -> Tuple[pd.DataFrame, pd.DataFrame]:
    frames = []
    status_rows = []
    using_private = has_service_account()

    for source in SHEET_SOURCES:
        try:
            if using_private:
                raw = read_private_sheet(source["gid"])
                mode = "Secure connection"
            else:
                raw = read_public_sheet(source["gid"])
                mode = "Live content stream"
            normalized = normalize_sheet(raw, source)
            frames.append(normalized)
            missing = [c for c in source["expected_columns"] if c not in raw.columns]
            status_rows.append({
                "Brand": source["brand"],
                "Stream": "Social Content Stream" if source["brand"] == "Social With Rocki" else "Cosmetology Content Stream",
                "GID": source["gid"],
                "Mode": mode,
                "Rows Pulled": len(raw),
                "Expected Columns": ", ".join(source["expected_columns"]),
                "Missing Expected Columns": ", ".join(missing) if missing else "None",
                "Status": "Connected",
                "Message": "Live customer content is available.",
            })
        except Exception as exc:
            status_rows.append({
                "Brand": source["brand"],
                "Stream": "Social Content Stream" if source["brand"] == "Social With Rocki" else "Cosmetology Content Stream",
                "GID": source["gid"],
                "Mode": "Secure connection" if using_private else "Live content stream",
                "Rows Pulled": 0,
                "Expected Columns": ", ".join(source["expected_columns"]),
                "Missing Expected Columns": "Unknown",
                "Status": "Not connected",
                "Message": str(exc),
            })

    if frames:
        data = pd.concat(frames, ignore_index=True)
        data["Row"] = range(1, len(data) + 1)
    else:
        data = pd.DataFrame(columns=[
            "Row", "Brand", "Source Sheet", "Source GID", "Source URL", "Source Row", "Trend", "Pillar", "Hook",
            "Search Intent", "Target Audience", "CTA", "Offer", "Content Pieces", "Total Words", "Total Characters",
            "Hashtag Count", "Mention Count", "CTA Signals", "Hook Signals", "Opportunity Score", "Readiness",
            "Completeness %", "Repurpose Score", "Last Refresh"
        ] + CHANNEL_COLUMNS)
    return data, pd.DataFrame(status_rows)


def build_long_df(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for _, row in df.iterrows():
        for column in CHANNEL_COLUMNS:
            content = str(row.get(column, "")).strip()
            if content:
                rows.append({
                    "Row": row.get("Row", ""),
                    "Brand": row.get("Brand", ""),
                    "Source Sheet": row.get("Source Sheet", ""),
                    "Source Row": row.get("Source Row", ""),
                    "Platform Key": column,
                    "Platform": DISPLAY_NAMES.get(column, column),
                    "Pillar": row.get("Pillar", ""),
                    "Trend": row.get("Trend", ""),
                    "Hook": row.get("Hook", ""),
                    "CTA": row.get("CTA", ""),
                    "Offer": row.get("Offer", ""),
                    "Content": content,
                    "Characters": len(content),
                    "Words": count_words(content),
                    "Sentences": count_sentences(content),
                    "Hashtags": ", ".join(extract_hashtags(content)),
                    "Hashtag Count": len(extract_hashtags(content)),
                    "Mentions": ", ".join(extract_mentions(content)),
                    "Mention Count": len(extract_mentions(content)),
                    "CTA Signals": count_cta_terms(content),
                    "Hook Signals": count_hook_terms(content),
                    "Opportunity Score": int(row.get("Opportunity Score", 0) or 0),
                    "Readiness": row.get("Readiness", ""),
                    "Repurpose Score": int(row.get("Repurpose Score", 0) or 0),
                })
    return pd.DataFrame(rows)


def metric_summary(df: pd.DataFrame, long_df: pd.DataFrame) -> Dict[str, Any]:
    if df.empty:
        return {
            "Rows": 0, "Assets": 0, "Brands": 0, "Platforms": 0, "Pillars": 0, "Words": 0, "Avg Words": 0,
            "Avg Chars": 0, "Hashtags": 0, "Mentions": 0, "CTA Signals": 0, "Hook Signals": 0,
            "Avg Score": 0, "High Score Assets": 0, "Completeness": 0, "Repurpose Clusters": 0,
            "Top Platform": "None", "Ready Rows": 0, "Short Form": 0, "Long Form": 0,
        }
    top_platform = "None"
    if not long_df.empty:
        counts = long_df["Platform"].value_counts()
        top_platform = str(counts.index[0]) if not counts.empty else "None"
    short_form_keys = {"Tiktok", "IG", "X"}
    long_form_keys = {"Blog", "Blog (AI Agent)", "Newsletter", "Podcast"}
    return {
        "Rows": len(df),
        "Assets": len(long_df),
        "Brands": df["Brand"].nunique(),
        "Platforms": long_df["Platform"].nunique() if not long_df.empty else 0,
        "Pillars": df["Pillar"].nunique(),
        "Words": int(long_df["Words"].sum()) if not long_df.empty else 0,
        "Avg Words": int(long_df["Words"].mean()) if not long_df.empty else 0,
        "Avg Chars": int(long_df["Characters"].mean()) if not long_df.empty else 0,
        "Hashtags": int(long_df["Hashtag Count"].sum()) if not long_df.empty else 0,
        "Mentions": int(long_df["Mention Count"].sum()) if not long_df.empty else 0,
        "CTA Signals": int(long_df["CTA Signals"].sum()) if not long_df.empty else 0,
        "Hook Signals": int(long_df["Hook Signals"].sum()) if not long_df.empty else 0,
        "Avg Score": round(float(df["Opportunity Score"].mean()), 1),
        "High Score Assets": int((long_df["Opportunity Score"] >= 8).sum()) if not long_df.empty else 0,
        "Completeness": round(float(df["Completeness %"].mean()), 1),
        "Repurpose Clusters": int((df["Content Pieces"] >= 6).sum()),
        "Top Platform": top_platform,
        "Ready Rows": int((df["Readiness"] == "Ready").sum()),
        "Short Form": int(long_df["Platform Key"].isin(short_form_keys).sum()) if not long_df.empty else 0,
        "Long Form": int(long_df["Platform Key"].isin(long_form_keys).sum()) if not long_df.empty else 0,
    }


def filtered_rows(df: pd.DataFrame, brands: List[str], query: str) -> pd.DataFrame:
    active = df[df["Brand"].isin(brands)].copy() if brands else df.copy()
    if query.strip() and not active.empty:
        cols = ["Brand", "Source Sheet", "Pillar", "Trend", "Hook", "CTA", "Offer", "Readiness"] + CHANNEL_COLUMNS
        available = [c for c in cols if c in active.columns]
        mask = active[available].apply(lambda c: c.astype(str).str.contains(query.strip(), case=False, na=False))
        active = active[mask.any(axis=1)]
    return active.reset_index(drop=True)


def display_table(df: pd.DataFrame, cols: List[str]) -> pd.DataFrame:
    available = [c for c in cols if c in df.columns]
    renamed = df[available].copy()
    rename_map = {
        "Source Sheet": "Content Stream",
        "Source Row": "Stream Row",
        "Source GID": "Stream ID",
        "Rows Pulled": "Rows Loaded",
    }
    return renamed.rename(columns=rename_map)


def render_login_page() -> None:
    st.markdown("""
    <div class="login-shell"><div class="login-card">
    <div class="eyebrow">Private Customer Content Studio</div>
    <div class="login-title">Brand For The Customer</div>
    <div class="muted">A mobile-first content command center for customer-facing brand assets, trend planning, repurposing, analytics, exports, and review workflows.</div>
    <div style="margin-top:16px"><span class="pill">Live Content Feed</span><span class="pill green">Customer Brand Metrics</span><span class="pill purple">CRUD Workspace</span></div>
    </div></div>
    """, unsafe_allow_html=True)
    left, center, right = st.columns([1, 1.1, 1])
    with center:
        st.markdown("<div class='glass-card'>", unsafe_allow_html=True)
        with st.form("login_form"):
            username = st.text_input("Username", placeholder="rocki")
            password = st.text_input("Password", type="password", placeholder="rocki2026")
            submitted = st.form_submit_button("Open Customer Studio", use_container_width=True)
        st.caption("Demo login: rocki / rocki2026")
        if submitted:
            if _check_login(username, password):
                _sign_in(username.strip())
                st.rerun()
            st.error("Invalid username or password.")
        st.markdown("</div>", unsafe_allow_html=True)


def render_hero(title: str, subtitle: str, badges: List[str]) -> None:
    badge_html = "".join(f"<span class='pill'>{escape(str(b))}</span>" for b in badges)
    st.markdown(f"""
    <div class="hero-card">
      <div class="eyebrow">Brand For The Customer</div>
      <h1 style="margin:8px 0 12px">{escape(title)}</h1>
      <div class="muted" style="max-width:980px">{escape(subtitle)}</div>
      <div style="margin-top:14px">{badge_html}</div>
    </div>
    """, unsafe_allow_html=True)


def render_sidebar(df: pd.DataFrame):
    with st.sidebar:
        st.markdown(f"""
        <div style='padding:.5rem 0 .25rem'>
          <div class='eyebrow'>Signed in</div>
          <div style='font-family:"Playfair Display",serif;font-size:1.55rem;color:#27151f;margin-top:4px;font-weight:900'>{escape(str(st.session_state.auth_name or 'Member'))}</div>
          <div class='muted'>{escape(str(st.session_state.auth_role or 'User'))}</div>
        </div>
        """, unsafe_allow_html=True)

        current = st.session_state.get("page", "Dashboard")
        index = PAGES.index(current) if current in PAGES else 0
        page_choice = st.radio("Pages", PAGES, index=index, label_visibility="collapsed")
        st.session_state.page = page_choice

        st.markdown("---")
        brand_options = sorted(df["Brand"].dropna().unique()) if not df.empty else [s["brand"] for s in SHEET_SOURCES]
        brands = st.multiselect("Brands", brand_options, default=brand_options)
        platforms = st.multiselect(
            "Platforms",
            CHANNEL_COLUMNS,
            default=CHANNEL_COLUMNS,
            format_func=lambda v: f"{PLATFORM_ICONS.get(v, '•')} {DISPLAY_NAMES.get(v, v)}",
        )
        query = st.text_input("Search content", placeholder="AI, client, student, kit, state board...")
        st.markdown("---")
        st.caption("Live customer content feed")
        if st.button("Refresh Live Content", use_container_width=True):
            st.cache_data.clear()
            st.rerun()
        if st.button("Sign Out", use_container_width=True):
            _sign_out()
    return st.session_state.page, brands, platforms, query


def render_metric_tiles(summary: Dict[str, Any]) -> None:
    rows = [
        [
            ("Content Rows", summary["Rows"], "Imported planning rows"),
            ("Content Assets", summary["Assets"], "Filled platform pieces"),
            ("Brands", summary["Brands"], "Active customer brands"),
            ("Platforms", summary["Platforms"], "Channels with content"),
            ("Pillars", summary["Pillars"], "Strategic categories"),
        ],
        [
            ("Total Words", f"{summary['Words']:,}", "All active copy"),
            ("Avg Words", summary["Avg Words"], "Per content asset"),
            ("Avg Characters", summary["Avg Chars"], "Per content asset"),
            ("Avg Score", summary["Avg Score"], "Opportunity rating"),
            ("Completeness", f"{summary['Completeness']}%", "Average row coverage"),
        ],
        [
            ("Hashtags", summary["Hashtags"], "Detected tags"),
            ("Mentions", summary["Mentions"], "Detected handles"),
            ("CTA Signals", summary["CTA Signals"], "Action language"),
            ("Hook Signals", summary["Hook Signals"], "Attention language"),
            ("Ready Rows", summary["Ready Rows"], "Strongest rows"),
        ],
        [
            ("Repurpose Clusters", summary["Repurpose Clusters"], "Rows with 6+ assets"),
            ("High Score Assets", summary["High Score Assets"], "Assets scoring 8+"),
            ("Short Form", summary["Short Form"], "TikTok / IG / X assets"),
            ("Long Form", summary["Long Form"], "Blog / email / podcast assets"),
            ("Top Platform", summary["Top Platform"], "Most filled channel"),
        ],
    ]

    for row in rows:
        cols = st.columns(len(row))
        for col, (label, value, help_text) in zip(cols, row):
            col.metric(label, value, help=help_text)


def render_page_buttons() -> None:
    st.markdown("### Fast Page Buttons")
    button_rows = [
        [("Customer Brand", "Open Customer Brand"), ("Content Library", "Open Library"), ("CRUD Studio", "Open CRUD Studio"), ("Analytics", "Open Analytics")],
        [("Trend Finder", "Open Trend Finder"), ("Content Calendar", "Open Calendar"), ("Export Center", "Open Exports"), ("Source Health", "Open Source Health")],
    ]
    for row in button_rows:
        cols = st.columns(len(row))
        for col, (page, label) in zip(cols, row):
            if col.button(label, use_container_width=True, key=f"goto_{page}"):
                goto_page(page)


def render_dashboard(df: pd.DataFrame, status_df: pd.DataFrame, brands: List[str], platforms: List[str], query: str) -> None:
    active = filtered_rows(df, brands, query)
    long_df = build_long_df(active)
    if platforms and not long_df.empty:
        long_df = long_df[long_df["Platform Key"].isin(platforms)]
    summary = metric_summary(active, long_df)

    render_hero(
        "Customer Brand Command Center",
        "A customer-facing content dashboard with richer metrics, fast navigation, review status, export tools, repurposing insights, and a local CRUD workspace that does not alter your existing source columns.",
        ["Brand For The Customer", "Metrics Expanded", "Mobile First", f"Updated {datetime.now().strftime('%b %d, %Y %I:%M %p')}"],
    )

    render_page_buttons()
    render_metric_tiles(summary)

    left, right = st.columns([1.35, .95], gap="large")
    with left:
        st.markdown("### Content Performance Snapshot")
        if not active.empty:
            brand_chart = active.groupby("Brand")[["Content Pieces", "Total Words", "Opportunity Score", "Repurpose Score"]].mean(numeric_only=True)
            st.bar_chart(brand_chart)

        st.markdown("### Priority Content Rows")
        cols = ["Row", "Brand", "Source Sheet", "Source Row", "Pillar", "Trend", "Readiness", "Content Pieces", "Total Words", "Completeness %", "Repurpose Score", "Opportunity Score"]
        table = display_table(active.sort_values(["Opportunity Score", "Repurpose Score"], ascending=[False, False]), cols)
        st.dataframe(
            table,
            use_container_width=True,
            hide_index=True,
            column_config={
                "Trend": st.column_config.TextColumn(width="large"),
                "Opportunity Score": st.column_config.ProgressColumn(min_value=0, max_value=10),
                "Completeness %": st.column_config.ProgressColumn(min_value=0, max_value=100),
                "Repurpose Score": st.column_config.ProgressColumn(min_value=0, max_value=100),
            },
        )
    with right:
        st.markdown("### Content Stream Health")
        for _, source in status_df.iterrows():
            status = "✅ Connected" if source["Status"] == "Connected" else "⚠️ Needs Attention"
            st.markdown(f"""
            <div class='mini-card'>
              <div class='eyebrow'>{safe_html(source['Brand'])}</div>
              <div class='content-title'>{status}</div>
              <div class='muted'>{safe_html(source['Stream'])}: {safe_html(source['Rows Pulled'])} rows loaded.</div>
            </div>
            """, unsafe_allow_html=True)

        st.markdown("### Customer Growth Checklist")
        st.markdown("""
        <div class='glass-card'>
          <ul class='check-list'>
            <li>Review highest-score rows first.</li>
            <li>Turn every strong row into short-form, long-form, email, and community copy.</li>
            <li>Move unfinished ideas into the CRUD Studio for editing.</li>
            <li>Export clean customer-ready files from Export Center.</li>
            <li>Use the calendar view to create a simple weekly publishing rhythm.</li>
          </ul>
        </div>
        """, unsafe_allow_html=True)


def render_customer_brand(df: pd.DataFrame, brands: List[str], query: str) -> None:
    active = filtered_rows(df, brands, query)
    long_df = build_long_df(active)
    summary = metric_summary(active, long_df)
    render_hero(
        "Brand For The Customer",
        "Customer-facing brand view for positioning, offers, content pillars, strongest hooks, audience promises, and ready-to-repurpose assets.",
        ["Customer Brand View", "Offer Ladder", "Pillar Map", "Copy Ready"],
    )

    render_metric_tiles(summary)

    st.markdown("### Customer Brand Strategy Cards")
    for brand in sorted(active["Brand"].unique()) if not active.empty else sorted(BRAND_STRATEGY.keys()):
        info = BRAND_STRATEGY.get(brand, {})
        brand_df = active[active["Brand"] == brand].copy() if not active.empty else pd.DataFrame()
        brand_long = build_long_df(brand_df)
        st.markdown(f"""
        <div class='glass-card'>
          <div class='brand-band'></div>
          <div class='eyebrow'>{safe_html(brand)}</div>
          <div class='content-title'>{safe_html(info.get('tagline', 'Customer brand content system'))}</div>
          <div class='content-copy'>{safe_html(info.get('promise', 'Create trust-building customer content.'))}</div>
          <div style='margin-top:12px'>
            <span class='pill green'>{safe_html(info.get('audience', 'Customer audience'))}</span>
            <span class='pill purple'>{len(brand_df)} rows</span>
            <span class='pill'>{len(brand_long)} assets</span>
          </div>
        </div>
        """, unsafe_allow_html=True)

        c1, c2 = st.columns([1.05, .95], gap="large")
        with c1:
            pillar_counts = brand_df["Pillar"].value_counts().reset_index()
            if not pillar_counts.empty:
                pillar_counts.columns = ["Pillar", "Rows"]
                st.markdown(f"#### {brand} Pillar Coverage")
                st.dataframe(pillar_counts, use_container_width=True, hide_index=True)
            else:
                st.info("No pillar data found yet.")
        with c2:
            st.markdown(f"#### {brand} Offer Ladder")
            offers = info.get("offers", [])
            st.markdown("<div class='mini-card'>" + "".join(f"<span class='pill purple'>{escape(o)}</span>" for o in offers) + "</div>", unsafe_allow_html=True)

    st.markdown("### Best Customer-Facing Hooks")
    if active.empty:
        st.info("No content rows match your current filters.")
    else:
        hooks = active[["Brand", "Pillar", "Trend", "Hook", "Offer", "Opportunity Score", "Repurpose Score"]].sort_values(
            ["Opportunity Score", "Repurpose Score"], ascending=[False, False]
        ).head(25)
        st.dataframe(
            hooks,
            use_container_width=True,
            hide_index=True,
            column_config={
                "Trend": st.column_config.TextColumn(width="large"),
                "Hook": st.column_config.TextColumn(width="large"),
                "Opportunity Score": st.column_config.ProgressColumn(min_value=0, max_value=10),
                "Repurpose Score": st.column_config.ProgressColumn(min_value=0, max_value=100),
            },
        )


def render_analytics(df: pd.DataFrame, brands: List[str], platforms: List[str], query: str) -> None:
    active = filtered_rows(df, brands, query)
    long_df = build_long_df(active)
    if platforms and not long_df.empty:
        long_df = long_df[long_df["Platform Key"].isin(platforms)]
    summary = metric_summary(active, long_df)
    render_hero(
        "Analytics",
        "Expanded metric view for brand coverage, platform depth, pillar balance, readiness, CTA strength, hooks, hashtags, words, and repurposing opportunities.",
        ["Expanded Metrics", "Platform Depth", "Readiness View"],
    )
    render_metric_tiles(summary)

    if active.empty or long_df.empty:
        st.info("No matching content is available for analytics.")
        return

    c1, c2 = st.columns(2, gap="large")
    with c1:
        st.markdown("### Assets by Platform")
        st.bar_chart(long_df.groupby("Platform")["Content"].count().sort_values(ascending=False))
        st.markdown("### Words by Platform")
        st.bar_chart(long_df.groupby("Platform")["Words"].sum().sort_values(ascending=False))
    with c2:
        st.markdown("### Rows by Pillar")
        st.bar_chart(active.groupby("Pillar")["Row"].count().sort_values(ascending=False))
        st.markdown("### Readiness Breakdown")
        readiness = active["Readiness"].value_counts().reindex(STATUS_ORDER, fill_value=0)
        st.bar_chart(readiness)

    st.markdown("### Platform Quality Table")
    platform_quality = long_df.groupby("Platform").agg(
        Assets=("Content", "count"),
        Words=("Words", "sum"),
        Avg_Words=("Words", "mean"),
        Avg_Characters=("Characters", "mean"),
        Hashtags=("Hashtag Count", "sum"),
        Mentions=("Mention Count", "sum"),
        CTA_Signals=("CTA Signals", "sum"),
        Hook_Signals=("Hook Signals", "sum"),
        Avg_Opportunity_Score=("Opportunity Score", "mean"),
        Avg_Repurpose_Score=("Repurpose Score", "mean"),
    ).reset_index()
    numeric_cols = platform_quality.select_dtypes(include="number").columns
    platform_quality[numeric_cols] = platform_quality[numeric_cols].round(1)
    st.dataframe(platform_quality, use_container_width=True, hide_index=True)

    st.markdown("### Brand + Pillar Matrix")
    matrix = active.pivot_table(index="Brand", columns="Pillar", values="Row", aggfunc="count", fill_value=0)
    st.dataframe(matrix, use_container_width=True)


def render_trend_finder(df: pd.DataFrame) -> None:
    render_hero(
        "Trend Finder",
        "Find customer content opportunities already present in your live content feed. Filter by brand, pillar, score, readiness, CTA strength, and repurpose potential.",
        ["Searchable", "Exportable", "Opportunity Scored"],
    )
    if df.empty:
        st.warning("No content rows are available yet.")
        return

    b1, b2, b3, b4 = st.columns([1, 1, 1, 1])
    with b1:
        brand_filter = st.multiselect("Brand", sorted(df["Brand"].unique()), default=sorted(df["Brand"].unique()))
    with b2:
        pillar_filter = st.multiselect("Pillar", sorted(df["Pillar"].unique()), default=sorted(df["Pillar"].unique()))
    with b3:
        min_score = st.slider("Minimum Opportunity Score", 0, 10, 0)
    with b4:
        min_repurpose = st.slider("Minimum Repurpose Score", 0, 100, 0)

    readiness_filter = st.multiselect("Readiness", STATUS_ORDER, default=STATUS_ORDER)
    active = df[
        df["Brand"].isin(brand_filter)
        & df["Pillar"].isin(pillar_filter)
        & df["Readiness"].isin(readiness_filter)
        & (df["Opportunity Score"].astype(int) >= min_score)
        & (df["Repurpose Score"].astype(int) >= min_repurpose)
    ].copy()

    st.download_button(
        "Download Trend Board CSV",
        data=active.to_csv(index=False).encode("utf-8"),
        file_name="customer_brand_trend_board.csv",
        mime="text/csv",
        use_container_width=True,
    )

    for _, row in active.sort_values(["Opportunity Score", "Repurpose Score"], ascending=[False, False]).iterrows():
        st.markdown(f"""
        <div class='content-card'>
          <div class='eyebrow'>{safe_html(row['Brand'])} • Row {safe_html(row['Row'])} • {safe_html(row['Readiness'])}</div>
          <div class='content-title'>{safe_html(row['Trend'])}</div>
          <div class='trend-copy'>
            <b>Pillar:</b> {safe_html(row['Pillar'])}<br>
            <b>Hook:</b> {safe_html(row['Hook'])}<br>
            <b>Audience:</b> {safe_html(row['Target Audience'])}<br>
            <b>CTA:</b> {safe_html(row['CTA'])}
          </div>
          <span class='pill purple'>Offer: {safe_html(row['Offer'])}</span>
          <span class='pill'>Score {safe_html(row['Opportunity Score'])}/10</span>
          <span class='pill green'>{safe_html(row['Content Pieces'])} assets</span>
          <span class='pill gold'>Repurpose {safe_html(row['Repurpose Score'])}/100</span>
        </div>
        """, unsafe_allow_html=True)


def render_content_library(df: pd.DataFrame, brands: List[str], platforms: List[str], query: str) -> None:
    active_rows = filtered_rows(df, brands, query)
    long_df = build_long_df(active_rows)
    if platforms and not long_df.empty:
        long_df = long_df[long_df["Platform Key"].isin(platforms)]
    render_hero(
        "Content Library",
        "Copy-ready customer content library with filters, metrics, cards, planning table, and export tools.",
        ["Copy Ready", "Customer Posts", "Filter + Export"],
    )

    if long_df.empty:
        st.info("No content matches the current filters.")
        return

    left, mid, right = st.columns([1, 1, 1])
    with left:
        pfilter = st.multiselect("Library Platform", sorted(long_df["Platform"].unique()), default=sorted(long_df["Platform"].unique()))
    with mid:
        brand_filter = st.multiselect("Library Brand", sorted(long_df["Brand"].unique()), default=sorted(long_df["Brand"].unique()))
    with right:
        min_chars = st.slider("Minimum Characters", 0, int(max(1000, long_df["Characters"].max())), 0)

    readiness_filter = st.multiselect("Asset Readiness", STATUS_ORDER, default=STATUS_ORDER)

    active = long_df[
        long_df["Platform"].isin(pfilter)
        & long_df["Brand"].isin(brand_filter)
        & long_df["Readiness"].isin(readiness_filter)
        & (long_df["Characters"] >= min_chars)
    ].copy()

    summary = metric_summary(active_rows, active)
    render_metric_tiles(summary)

    export_cols = [
        "Brand", "Source Sheet", "Source Row", "Platform", "Pillar", "Trend", "Hook", "CTA", "Offer", "Readiness",
        "Content", "Characters", "Words", "Sentences", "Hashtags", "Mentions", "CTA Signals", "Hook Signals",
        "Opportunity Score", "Repurpose Score",
    ]
    st.download_button(
        "Download Active Content CSV",
        data=active[export_cols].rename(columns={"Source Sheet": "Content Stream", "Source Row": "Stream Row"}).to_csv(index=False).encode("utf-8"),
        file_name="customer_brand_content_library.csv",
        mime="text/csv",
        use_container_width=True,
    )

    st.markdown("### Copy-Ready Cards")
    for idx, row in active.reset_index(drop=True).iterrows():
        icon = PLATFORM_ICONS.get(str(row.get("Platform Key", "")), "✨")
        st.markdown(f"""
        <div class='content-card'>
          <div class='eyebrow'>{safe_html(row['Brand'])} • Row {safe_html(row['Row'])} • {safe_html(row['Pillar'])} • {safe_html(row['Readiness'])}</div>
          <div class='content-title'>{icon} {safe_html(row['Platform'])}: {safe_html(row['Trend'])}</div>
          <div class='trend-copy'>
            <b>Hook:</b> {safe_html(row['Hook'])}<br>
            <b>CTA:</b> {safe_html(row['CTA'])}<br>
            <b>Offer:</b> {safe_html(row['Offer'])}
          </div>
          <span class='pill purple'>{safe_html(row['Characters'])} chars</span>
          <span class='pill green'>{safe_html(row['Words'])} words</span>
          <span class='pill'>Score {safe_html(row['Opportunity Score'])}/10</span>
          <span class='pill gold'>{safe_html(row['Hashtags'])}</span>
        </div>
        """, unsafe_allow_html=True)
        st.text_area(
            "Copy content",
            value=str(row["Content"]),
            height=250 if int(row["Characters"]) > 900 else 170,
            key=f"copy_{row['Row']}_{row['Platform Key']}_{idx}",
            label_visibility="collapsed",
        )

    st.markdown("### Planning Table")
    st.dataframe(
        active[export_cols].rename(columns={"Source Sheet": "Content Stream", "Source Row": "Stream Row"}),
        use_container_width=True,
        hide_index=True,
        column_config={
            "Trend": st.column_config.TextColumn(width="large"),
            "Content": st.column_config.TextColumn(width="large"),
            "Opportunity Score": st.column_config.ProgressColumn(min_value=0, max_value=10),
            "Repurpose Score": st.column_config.ProgressColumn(min_value=0, max_value=100),
        },
    )


def render_calendar(df: pd.DataFrame, brands: List[str], query: str) -> None:
    active = filtered_rows(df, brands, query)
    render_hero(
        "Content Calendar",
        "A customer publishing view built from active content rows. Use it to plan weekly campaigns, repurpose assets, and assign primary platforms.",
        ["Weekly Planning", "Repurpose Map", "Exportable"],
    )
    if active.empty:
        st.info("No content rows available for calendar planning.")
        return

    records = []
    for idx, row in active.reset_index(drop=True).iterrows():
        week = (idx // 5) + 1
        day = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"][idx % 5]
        records.append({
            "Week": week,
            "Day": day,
            "Brand": row.get("Brand", ""),
            "Row": row.get("Row", ""),
            "Primary Platform": "TikTok + Instagram" if row.get("Brand") == "Cosmetology With Rocki" else "LinkedIn + Instagram",
            "Secondary Platforms": "Pinterest, Facebook, Newsletter, Blog",
            "Trend / Topic": row.get("Trend", ""),
            "Readiness": row.get("Readiness", ""),
            "Repurpose Plan": "Turn the strongest idea into short video, carousel, email, blog, and community post.",
            "CTA": row.get("CTA", ""),
            "Offer": row.get("Offer", ""),
            "Score": row.get("Opportunity Score", 0),
            "Repurpose Score": row.get("Repurpose Score", 0),
        })
    cal = pd.DataFrame(records)
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Calendar Items", len(cal))
    c2.metric("Weeks", cal["Week"].nunique())
    c3.metric("Ready Items", int((cal["Readiness"] == "Ready").sum()))
    c4.metric("Avg Score", round(float(cal["Score"].mean()), 1))

    st.dataframe(
        cal,
        use_container_width=True,
        hide_index=True,
        column_config={
            "Trend / Topic": st.column_config.TextColumn(width="large"),
            "Repurpose Plan": st.column_config.TextColumn(width="medium"),
            "Score": st.column_config.ProgressColumn(min_value=0, max_value=10),
            "Repurpose Score": st.column_config.ProgressColumn(min_value=0, max_value=100),
        },
    )
    st.download_button(
        "Download Content Calendar CSV",
        data=cal.to_csv(index=False).encode("utf-8"),
        file_name="customer_brand_content_calendar.csv",
        mime="text/csv",
        use_container_width=True,
    )


def make_draft_id() -> str:
    return f"DRAFT-{datetime.now().strftime('%Y%m%d%H%M%S%f')}"


def drafts_df() -> pd.DataFrame:
    drafts = st.session_state.get("customer_drafts", [])
    if not drafts:
        return pd.DataFrame(columns=[
            "Draft ID", "Brand", "Platform", "Pillar", "Trend", "Hook", "Content", "CTA", "Offer", "Status",
            "Owner", "Due Date", "Created", "Updated", "Words", "Characters", "Score",
        ])
    return pd.DataFrame(drafts)


def render_crud_studio(df: pd.DataFrame, brands: List[str], query: str) -> None:
    active = filtered_rows(df, brands, query)
    render_hero(
        "CRUD Studio",
        "Create, review, update, duplicate, delete, and export customer content drafts inside this dashboard session without altering your existing source columns.",
        ["Create", "Read", "Update", "Delete", "Duplicate", "Export"],
    )

    tabs = st.tabs(["Create Draft", "Manage Drafts", "Import From Content Row", "Draft Metrics"])

    with tabs[0]:
        st.markdown("### Create Customer Content Draft")
        with st.form("create_draft_form", clear_on_submit=True):
            c1, c2, c3 = st.columns(3)
            with c1:
                brand = st.selectbox("Brand", sorted(BRAND_STRATEGY.keys()))
                platform = st.selectbox("Platform", CHANNEL_COLUMNS, format_func=lambda v: f"{PLATFORM_ICONS.get(v, '•')} {DISPLAY_NAMES.get(v, v)}")
                status = st.selectbox("Status", STATUS_ORDER, index=1)
            with c2:
                pillar_options = BRAND_STRATEGY.get(brand, {}).get("pillars", [])
                pillar = st.selectbox("Pillar", pillar_options if pillar_options else ["Customer Content"])
                owner = st.text_input("Owner", value=str(st.session_state.auth_name or "Team"))
                due_date = st.date_input("Due Date")
            with c3:
                offer_options = BRAND_STRATEGY.get(brand, {}).get("offers", [])
                offer = st.selectbox("Offer", offer_options if offer_options else ["Customer Offer"])
                trend = st.text_input("Trend / Topic", placeholder="Enter customer-facing topic")
                hook = st.text_input("Hook", placeholder="Enter first-line hook")
            content = st.text_area("Content", height=220, placeholder="Write or paste the post, email, script, or campaign copy...")
            cta = st.text_input("CTA", placeholder="Example: Save this, comment READY, book a call, download the checklist")
            submitted = st.form_submit_button("Create Draft", use_container_width=True)
        if submitted:
            now = datetime.now().strftime("%Y-%m-%d %I:%M %p")
            draft = {
                "Draft ID": make_draft_id(),
                "Brand": brand,
                "Platform": platform,
                "Pillar": pillar,
                "Trend": trend,
                "Hook": hook,
                "Content": content,
                "CTA": cta,
                "Offer": offer,
                "Status": status,
                "Owner": owner,
                "Due Date": str(due_date),
                "Created": now,
                "Updated": now,
                "Words": count_words(content),
                "Characters": len(content),
                "Score": min(10, 2 + min(3, count_words(content) // 70) + min(2, count_cta_terms(content) + count_cta_terms(cta)) + min(2, count_hook_terms(content) + count_hook_terms(hook)) + min(1, len(extract_hashtags(content)))),
            }
            st.session_state.customer_drafts.append(draft)
            st.success("Draft created.")

    with tabs[1]:
        current = drafts_df()
        st.markdown("### Manage Customer Drafts")
        if current.empty:
            st.info("No session drafts yet. Create one or import from an existing content row.")
        else:
            c1, c2, c3 = st.columns(3)
            with c1:
                status_filter = st.multiselect("Status Filter", STATUS_ORDER, default=STATUS_ORDER)
            with c2:
                brand_filter = st.multiselect("Draft Brand Filter", sorted(current["Brand"].unique()), default=sorted(current["Brand"].unique()))
            with c3:
                platform_filter = st.multiselect("Draft Platform Filter", sorted(current["Platform"].unique()), default=sorted(current["Platform"].unique()))
            filtered = current[
                current["Status"].isin(status_filter)
                & current["Brand"].isin(brand_filter)
                & current["Platform"].isin(platform_filter)
            ].copy()
            st.dataframe(filtered, use_container_width=True, hide_index=True)

            selected_id = st.selectbox("Select draft to edit", filtered["Draft ID"].tolist() if not filtered.empty else current["Draft ID"].tolist())
            draft_index = next((i for i, item in enumerate(st.session_state.customer_drafts) if item["Draft ID"] == selected_id), None)
            if draft_index is not None:
                draft = st.session_state.customer_drafts[draft_index]
                with st.form("update_draft_form"):
                    c1, c2, c3 = st.columns(3)
                    with c1:
                        new_brand = st.selectbox("Edit Brand", sorted(BRAND_STRATEGY.keys()), index=sorted(BRAND_STRATEGY.keys()).index(draft["Brand"]) if draft["Brand"] in sorted(BRAND_STRATEGY.keys()) else 0)
                        new_platform = st.selectbox("Edit Platform", CHANNEL_COLUMNS, index=CHANNEL_COLUMNS.index(draft["Platform"]) if draft["Platform"] in CHANNEL_COLUMNS else 0, format_func=lambda v: f"{PLATFORM_ICONS.get(v, '•')} {DISPLAY_NAMES.get(v, v)}")
                        new_status = st.selectbox("Edit Status", STATUS_ORDER, index=STATUS_ORDER.index(draft["Status"]) if draft["Status"] in STATUS_ORDER else 1)
                    with c2:
                        pillar_options = BRAND_STRATEGY.get(new_brand, {}).get("pillars", [])
                        new_pillar = st.selectbox("Edit Pillar", pillar_options if pillar_options else [draft.get("Pillar", "Customer Content")], index=0)
                        new_owner = st.text_input("Edit Owner", value=draft.get("Owner", "Team"))
                        new_due_date = st.text_input("Edit Due Date", value=str(draft.get("Due Date", "")))
                    with c3:
                        offer_options = BRAND_STRATEGY.get(new_brand, {}).get("offers", [])
                        existing_offer = draft.get("Offer", "")
                        offer_index = offer_options.index(existing_offer) if existing_offer in offer_options else 0
                        new_offer = st.selectbox("Edit Offer", offer_options if offer_options else [existing_offer or "Customer Offer"], index=offer_index)
                        new_trend = st.text_input("Edit Trend / Topic", value=draft.get("Trend", ""))
                        new_hook = st.text_input("Edit Hook", value=draft.get("Hook", ""))
                    new_content = st.text_area("Edit Content", value=draft.get("Content", ""), height=260)
                    new_cta = st.text_input("Edit CTA", value=draft.get("CTA", ""))
                    update_btn = st.form_submit_button("Update Draft", use_container_width=True)
                if update_btn:
                    now = datetime.now().strftime("%Y-%m-%d %I:%M %p")
                    st.session_state.customer_drafts[draft_index].update({
                        "Brand": new_brand,
                        "Platform": new_platform,
                        "Pillar": new_pillar,
                        "Trend": new_trend,
                        "Hook": new_hook,
                        "Content": new_content,
                        "CTA": new_cta,
                        "Offer": new_offer,
                        "Status": new_status,
                        "Owner": new_owner,
                        "Due Date": new_due_date,
                        "Updated": now,
                        "Words": count_words(new_content),
                        "Characters": len(new_content),
                        "Score": min(10, 2 + min(3, count_words(new_content) // 70) + min(2, count_cta_terms(new_content) + count_cta_terms(new_cta)) + min(2, count_hook_terms(new_content) + count_hook_terms(new_hook)) + min(1, len(extract_hashtags(new_content)))),
                    })
                    st.success("Draft updated.")
                    st.rerun()

                d1, d2 = st.columns(2)
                if d1.button("Duplicate Selected Draft", use_container_width=True):
                    new_draft = dict(draft)
                    new_draft["Draft ID"] = make_draft_id()
                    new_draft["Trend"] = f"{new_draft.get('Trend', '')} Copy".strip()
                    new_draft["Created"] = datetime.now().strftime("%Y-%m-%d %I:%M %p")
                    new_draft["Updated"] = new_draft["Created"]
                    st.session_state.customer_drafts.append(new_draft)
                    st.success("Draft duplicated.")
                    st.rerun()
                if d2.button("Delete Selected Draft", use_container_width=True):
                    st.session_state.customer_drafts = [item for item in st.session_state.customer_drafts if item["Draft ID"] != selected_id]
                    st.success("Draft deleted.")
                    st.rerun()

            export = drafts_df()
            st.download_button(
                "Download Session Drafts CSV",
                data=export.to_csv(index=False).encode("utf-8"),
                file_name="customer_brand_session_drafts.csv",
                mime="text/csv",
                use_container_width=True,
            )

    with tabs[2]:
        st.markdown("### Import Existing Content Row Into Drafts")
        if active.empty:
            st.info("No active rows match current filters.")
        else:
            import_table = active[["Row", "Brand", "Pillar", "Trend", "Hook", "Offer", "Readiness", "Opportunity Score"]].copy()
            st.dataframe(import_table, use_container_width=True, hide_index=True)
            selected_row = st.selectbox("Choose row", active["Row"].tolist())
            selected_platform = st.selectbox("Choose platform to import", CHANNEL_COLUMNS, format_func=lambda v: f"{PLATFORM_ICONS.get(v, '•')} {DISPLAY_NAMES.get(v, v)}")
            if st.button("Import Selected Row As Draft", use_container_width=True):
                row = active[active["Row"] == selected_row].iloc[0]
                content = str(row.get(selected_platform, "")).strip()
                if not content:
                    st.error("Selected platform is empty for this row.")
                else:
                    now = datetime.now().strftime("%Y-%m-%d %I:%M %p")
                    draft = {
                        "Draft ID": make_draft_id(),
                        "Brand": row.get("Brand", ""),
                        "Platform": selected_platform,
                        "Pillar": row.get("Pillar", ""),
                        "Trend": row.get("Trend", ""),
                        "Hook": row.get("Hook", ""),
                        "Content": content,
                        "CTA": row.get("CTA", ""),
                        "Offer": row.get("Offer", ""),
                        "Status": row.get("Readiness", "Draft"),
                        "Owner": str(st.session_state.auth_name or "Team"),
                        "Due Date": "",
                        "Created": now,
                        "Updated": now,
                        "Words": count_words(content),
                        "Characters": len(content),
                        "Score": int(row.get("Opportunity Score", 0) or 0),
                    }
                    st.session_state.customer_drafts.append(draft)
                    st.success("Content imported into drafts.")

    with tabs[3]:
        current = drafts_df()
        st.markdown("### Draft Metrics")
        if current.empty:
            st.info("No drafts to measure yet.")
        else:
            c1, c2, c3, c4, c5 = st.columns(5)
            c1.metric("Drafts", len(current))
            c2.metric("Ready", int((current["Status"] == "Ready").sum()))
            c3.metric("Words", f"{int(current['Words'].sum()):,}")
            c4.metric("Avg Score", round(float(current["Score"].mean()), 1))
            c5.metric("Platforms", current["Platform"].nunique())
            st.markdown("### Drafts by Status")
            st.bar_chart(current["Status"].value_counts().reindex(STATUS_ORDER, fill_value=0))
            st.markdown("### Drafts by Platform")
            st.bar_chart(current["Platform"].value_counts())


def render_export_center(df: pd.DataFrame, brands: List[str], platforms: List[str], query: str) -> None:
    active_rows = filtered_rows(df, brands, query)
    long_df = build_long_df(active_rows)
    if platforms and not long_df.empty:
        long_df = long_df[long_df["Platform Key"].isin(platforms)]

    render_hero(
        "Export Center",
        "Download customer-ready files for full rows, platform content, calendar planning, trend boards, and session drafts.",
        ["CSV Exports", "Customer Ready", "No Column Changes"],
    )

    if active_rows.empty:
        st.info("No active content rows match current filters.")
        return

    full_export = active_rows.copy()
    library_export = long_df.copy()
    calendar_records = []
    for idx, row in active_rows.reset_index(drop=True).iterrows():
        calendar_records.append({
            "Week": (idx // 5) + 1,
            "Day": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"][idx % 5],
            "Brand": row.get("Brand", ""),
            "Topic": row.get("Trend", ""),
            "Pillar": row.get("Pillar", ""),
            "Primary Platform": "TikTok + Instagram" if row.get("Brand") == "Cosmetology With Rocki" else "LinkedIn + Instagram",
            "CTA": row.get("CTA", ""),
            "Offer": row.get("Offer", ""),
            "Readiness": row.get("Readiness", ""),
            "Opportunity Score": row.get("Opportunity Score", 0),
            "Repurpose Score": row.get("Repurpose Score", 0),
        })
    calendar_export = pd.DataFrame(calendar_records)
    trend_export = active_rows[["Brand", "Pillar", "Trend", "Hook", "Target Audience", "CTA", "Offer", "Readiness", "Content Pieces", "Total Words", "Opportunity Score", "Repurpose Score"]].copy()
    draft_export = drafts_df()

    c1, c2 = st.columns(2)
    with c1:
        st.markdown("### Main Exports")
        st.download_button("Download Full Content Rows", data=full_export.to_csv(index=False).encode("utf-8"), file_name="customer_brand_full_rows.csv", mime="text/csv", use_container_width=True)
        st.download_button("Download Platform Content Library", data=library_export.to_csv(index=False).encode("utf-8"), file_name="customer_brand_platform_library.csv", mime="text/csv", use_container_width=True)
        st.download_button("Download Calendar Planner", data=calendar_export.to_csv(index=False).encode("utf-8"), file_name="customer_brand_calendar_planner.csv", mime="text/csv", use_container_width=True)
    with c2:
        st.markdown("### Planning Exports")
        st.download_button("Download Trend Board", data=trend_export.to_csv(index=False).encode("utf-8"), file_name="customer_brand_trend_board.csv", mime="text/csv", use_container_width=True)
        st.download_button("Download Session Drafts", data=draft_export.to_csv(index=False).encode("utf-8"), file_name="customer_brand_session_drafts.csv", mime="text/csv", use_container_width=True)
        st.download_button("Download Column Template", data=pd.DataFrame(columns=CHANNEL_COLUMNS).to_csv(index=False).encode("utf-8"), file_name="customer_brand_column_template.csv", mime="text/csv", use_container_width=True)

    st.markdown("### Export Preview")
    st.dataframe(trend_export, use_container_width=True, hide_index=True)


def render_source_health(status_df: pd.DataFrame) -> None:
    render_hero(
        "Source Health",
        "Connection and column health for the two live customer content streams. This page keeps the source setup readable without changing any columns.",
        ["Connection Check", "Column Check", "Read Only"],
    )
    st.markdown("### Connected Content Streams")
    for _, row in status_df.iterrows():
        ok = row["Status"] == "Connected"
        status_class = "source-ok" if ok else "source-bad"
        st.markdown(f"""
        <div class='content-card'>
          <div class='eyebrow'>{safe_html(row['Brand'])}</div>
          <div class='content-title'>{safe_html(row['Stream'])}</div>
          <div class='trend-copy'>
            <b>Status:</b> <span class='{status_class}'>{safe_html(row['Status'])}</span><br>
            <b>Mode:</b> {safe_html(row['Mode'])}<br>
            <b>Rows loaded:</b> {safe_html(row['Rows Pulled'])}<br>
            <b>Expected columns:</b> {safe_html(row['Expected Columns'])}<br>
            <b>Missing columns:</b> {safe_html(row['Missing Expected Columns'])}<br>
            <b>Message:</b> {safe_html(row['Message'])}
          </div>
          <span class='pill'>Live Feed</span><span class='pill green'>Column Safe</span>
        </div>
        """, unsafe_allow_html=True)

    health_table = status_df[["Brand", "Stream", "Mode", "Rows Pulled", "Missing Expected Columns", "Status", "Message"]].rename(columns={"Rows Pulled": "Rows Loaded"})
    st.dataframe(health_table, use_container_width=True, hide_index=True)


def render_app() -> None:
    df, status_df = load_content_streams()
    page, brands, platforms, query = render_sidebar(df)

    if page == "Dashboard":
        render_dashboard(df, status_df, brands, platforms, query)
    elif page == "Customer Brand":
        render_customer_brand(df, brands, query)
    elif page == "Analytics":
        render_analytics(df, brands, platforms, query)
    elif page == "Trend Finder":
        render_trend_finder(filtered_rows(df, brands, query))
    elif page == "Content Library":
        render_content_library(df, brands, platforms, query)
    elif page == "Content Calendar":
        render_calendar(df, brands, query)
    elif page == "CRUD Studio":
        render_crud_studio(df, brands, query)
    elif page == "Export Center":
        render_export_center(df, brands, platforms, query)
    else:
        render_source_health(status_df)


_init_state()
if not st.session_state.auth_ok:
    render_login_page()
else:
    render_app()
