import hashlib
import re
from datetime import datetime
from html import escape
from typing import Any, Dict, List, Tuple

import pandas as pd
import streamlit as st

try:
    import gspread
    from google.oauth2.service_account import Credentials
except Exception:  # optional private-sheet support
    gspread = None
    Credentials = None

st.set_page_config(
    page_title="Rocki Google Sheets Content Studio",
    page_icon="💗",
    layout="wide",
    initial_sidebar_state="expanded",
)

SPREADSHEET_ID = "13p7C3RIhUZ0yfIcRFbSbfI6YY-P8Lmyn1AWbbQ9K9I8"
SPREADSHEET_URL = f"https://docs.google.com/spreadsheets/d/{SPREADSHEET_ID}/edit"

SHEET_SOURCES = [
    {
        "brand": "Social With Rocki",
        "sheet_name": "Sheet1",
        "gid": "213898480",
        "description": "General Social With Rocki content generated by the first n8n Google Sheets append node.",
        "expected_columns": [
            "Blog", "Newsletter", "Podcast", "Pinterest", "Facebook", "X", "Linkedin", "Tiktok", "IG", "Blog (AI Agent)"
        ],
    },
    {
        "brand": "Cosmetology With Rocki",
        "sheet_name": "rocki_cosmetology_7_day_demo_content",
        "gid": "835739923",
        "description": "Rocki cosmetology content generated by the second n8n Google Sheets append node.",
        "expected_columns": [
            "Research Strategy", "Blog", "Newsletter", "Podcast", "Pinterest", "Facebook", "X", "Linkedin", "Tiktok", "IG"
        ],
    },
]

CHANNEL_COLUMNS = [
    "Research Strategy", "Blog", "Blog (AI Agent)", "Newsletter", "Podcast", "Pinterest", "Facebook", "X", "Linkedin", "Tiktok", "IG"
]
DISPLAY_NAMES = {
    "Research Strategy": "Research Strategy",
    "Blog": "Blog",
    "Blog (AI Agent)": "AI Agent Blog",
    "Newsletter": "Newsletter",
    "Podcast": "Podcast",
    "Pinterest": "Pinterest",
    "Facebook": "Facebook",
    "X": "X / Twitter",
    "Linkedin": "LinkedIn",
    "Tiktok": "TikTok",
    "IG": "Instagram",
}
PLATFORM_ICONS = {
    "Research Strategy": "🧠",
    "Blog": "📝",
    "Blog (AI Agent)": "🤖",
    "Newsletter": "💌",
    "Podcast": "🎙️",
    "Pinterest": "📌",
    "Facebook": "👥",
    "X": "⚡",
    "Linkedin": "💼",
    "Tiktok": "🎬",
    "IG": "📸",
}

BRAND_STRATEGY = {
    "Social With Rocki": {
        "tagline": "Marketing, content systems, visibility, AI workflows, and monetization for beauty entrepreneurs.",
        "audience": "Beauty entrepreneurs, creators, salon owners, coaches, service providers, and future stylists building visibility.",
        "promise": "Turn content into trust, trust into community, and community into booked calls, subscribers, referrals, and paid offers.",
        "pillars": ["AI Content Systems", "Search-First Social", "Creator Brand Authority", "Client Proof Content", "Newsletter + Community", "Social Commerce", "Beauty Business Marketing"],
        "offers": ["7-Day Beauty Content Batch Kit", "Search-First Caption Bank", "Beauty Brand Audit", "Salon FAQ + AEO Pack", "LinkedIn Authority Pack", "Content Calendar Setup"],
    },
    "Cosmetology With Rocki": {
        "tagline": "Beauty school diary, cosmetology student survival, salon business lessons, and confidence-building content.",
        "audience": "Cosmetology students, future hairstylists, beauty school beginners, student stylists, and future salon owners.",
        "promise": "Help students survive school, document the journey, understand the business side, and build client-attraction confidence before graduation.",
        "pillars": ["Beauty School Survival", "Student Diary Series", "Marketing Meets Cosmetology", "Business Behind The Chair", "State Board Prep", "Client Experience", "Hair + Scalp Wellness"],
        "offers": ["Beauty School Starter Checklist", "Cosmetology Kit Audit Sheet", "State Board Study Planner", "Student Stylist Content Kit", "Salon Career Path Planner"],
    },
}

THEME = """
<style>
@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700;900&family=Poppins:wght@300;400;500;600;700;800&display=swap');
:root{--bg:#fff7fb;--ink:#24151f;--muted:#765a6d;--pink:#e11d74;--purple:#8b5cf6;--teal:#14b8a6;--cream:#fffaf2;--line:rgba(225,29,116,.16);--shadow:0 18px 48px rgba(120,30,85,.12)}
html, body, [data-testid="stAppViewContainer"]{background:radial-gradient(circle at 8% 0%,rgba(225,29,116,.18),transparent 27%),radial-gradient(circle at 90% 7%,rgba(139,92,246,.17),transparent 30%),linear-gradient(180deg,#fff7fb 0%,#fffaf2 52%,#fff7fb 100%)!important;font-family:'Poppins',sans-serif!important;color:var(--ink)!important}
[data-testid="stMain"]{background:transparent!important} [data-testid="stSidebar"]{background:linear-gradient(180deg,rgba(255,255,255,.97),rgba(255,239,247,.98))!important;border-right:1px solid var(--line)!important;box-shadow:8px 0 36px rgba(225,29,116,.07)}
[data-testid="stSidebar"] *{color:var(--ink)!important} header,footer,#MainMenu,[data-testid="stToolbar"],[data-testid="stDecoration"],[data-testid="stStatusWidget"],[data-testid="stHeaderActionElements"]{display:none!important;visibility:hidden!important;height:0!important}
div.block-container{padding-top:1.25rem!important;padding-bottom:2rem!important;max-width:1560px!important} h1,h2,h3{font-family:'Playfair Display',serif!important;letter-spacing:-.03em} h1{font-size:clamp(2.1rem,4vw,4.9rem)!important;line-height:.95!important;color:var(--ink)!important} h2{color:#3a1630!important} h3{color:var(--pink)!important}
[data-testid="stMetric"]{background:rgba(255,255,255,.78)!important;border:1px solid var(--line)!important;border-radius:24px!important;padding:18px 20px!important;box-shadow:var(--shadow)!important}[data-testid="stMetricValue"]{color:var(--pink)!important;font-family:'Playfair Display',serif!important;font-size:2.28rem!important}[data-testid="stMetricLabel"]{color:var(--muted)!important;font-weight:800!important}
.stButton>button,.stDownloadButton>button,button[kind="primary"]{background:linear-gradient(135deg,var(--pink),var(--purple))!important;color:#fff!important;border:0!important;border-radius:999px!important;font-weight:800!important;padding:.68rem 1.2rem!important;box-shadow:0 10px 28px rgba(225,29,116,.22)!important}.stTextInput input,.stTextArea textarea,[data-baseweb="select"]>div{background:rgba(255,255,255,.9)!important;border:1px solid rgba(225,29,116,.18)!important;border-radius:16px!important;color:var(--ink)!important}
.hero-card,.glass-card,.mini-card,.content-card,.action-card{border-radius:28px;border:1px solid var(--line)}.hero-card{position:relative;overflow:hidden;background:radial-gradient(circle at 88% 12%,rgba(20,184,166,.19),transparent 21%),radial-gradient(circle at 10% 8%,rgba(251,113,133,.24),transparent 24%),linear-gradient(135deg,rgba(255,255,255,.93),rgba(255,232,243,.84));padding:clamp(24px,4vw,46px);margin-bottom:18px;box-shadow:var(--shadow)}.glass-card,.mini-card,.content-card,.action-card{background:rgba(255,255,255,.78);box-shadow:var(--shadow);backdrop-filter:blur(14px)}.glass-card{padding:24px;margin-bottom:18px}.mini-card{padding:18px;margin-bottom:14px}.content-card{padding:22px;margin-bottom:18px}.action-card{padding:18px 20px;margin-bottom:14px}
.login-shell{max-width:1050px;margin:3rem auto 0;padding:1px;background:linear-gradient(135deg,rgba(225,29,116,.35),rgba(139,92,246,.26),rgba(20,184,166,.22));box-shadow:var(--shadow);border-radius:28px}.login-card{background:radial-gradient(circle at top right,rgba(225,29,116,.18),transparent 30%),linear-gradient(180deg,#fff,#fff0f7);padding:34px;border-radius:28px}.login-title{font-family:'Playfair Display',serif;font-size:clamp(2.5rem,6vw,5.3rem);font-weight:900;line-height:.92;margin:8px 0 14px;color:var(--ink)}
.eyebrow{color:var(--pink);font-size:.72rem;font-weight:900;letter-spacing:.16em;text-transform:uppercase}.muted{color:var(--muted);font-size:.93rem;line-height:1.65}.content-title{color:var(--ink);font-size:1.08rem;font-weight:900;margin:6px 0 10px}.content-copy{color:#3d2333;line-height:1.78;font-size:.93rem;white-space:pre-wrap;word-break:break-word}.trend-copy{color:#7b365e;line-height:1.66;font-size:.86rem;white-space:pre-wrap;word-break:break-word;border-left:3px solid rgba(225,29,116,.32);padding-left:12px;margin:10px 0 14px}.pill{display:inline-block;border-radius:999px;padding:6px 11px;margin:4px 6px 4px 0;background:rgba(225,29,116,.08);border:1px solid rgba(225,29,116,.16);color:#a41454;font-size:.76rem;font-weight:900}.pill.green{background:rgba(20,184,166,.12);border-color:rgba(20,184,166,.22);color:#0f766e}.pill.purple{background:rgba(139,92,246,.12);border-color:rgba(139,92,246,.2);color:#5b2fc7}.pill.gold{background:rgba(245,158,11,.12);border-color:rgba(245,158,11,.25);color:#92400e}
.card-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px;margin:12px 0 20px}.platform-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:16px;margin:12px 0 20px}.big-number{font-family:'Playfair Display',serif;font-size:2.25rem;font-weight:900;color:var(--pink);line-height:1}.check-list{margin:0;padding-left:1.1rem}.check-list li{margin-bottom:.55rem;color:#48283b;line-height:1.6}.progress-wrap{width:100%;height:10px;border-radius:999px;background:#f6d9e8;overflow:hidden;margin-top:10px}.progress-fill{height:100%;border-radius:999px;background:linear-gradient(90deg,var(--pink),var(--purple),var(--teal))}.brand-band{height:8px;border-radius:999px;margin-bottom:12px;background:linear-gradient(90deg,var(--pink),var(--purple),var(--teal))}.copybox{font-size:.85rem!important}.source-ok{color:#0f766e;font-weight:900}.source-bad{color:#b91c1c;font-weight:900}
@media(max-width:760px){div.block-container{padding-left:1rem!important;padding-right:1rem!important}.hero-card,.glass-card,.content-card{border-radius:22px;padding:20px}.platform-grid,.card-grid{grid-template-columns:1fr}[data-testid="stMetric"]{padding:14px!important}}
</style>
"""
st.markdown(THEME, unsafe_allow_html=True)


def safe_html(value: Any) -> str:
    return escape(str(value or ""))


def _hash_password(password: str) -> str:
    return hashlib.sha256(password.encode("utf-8")).hexdigest()


def _init_state() -> None:
    defaults = {"auth_ok": False, "auth_user": None, "auth_name": None, "auth_role": None}
    for key, value in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = value


USERS = {
    "rocki": {"name": "Rocki", "role": "Content Studio Admin", "password_hash": _hash_password("rocki2026")},
    "admin": {"name": "Admin", "role": "Content Studio Admin", "password_hash": _hash_password("rocki2026")},
}


def _check_login(username: str, password: str) -> bool:
    record = USERS.get((username or "").strip().lower())
    return bool(record and record["password_hash"] == _hash_password(password or ""))


def _sign_in(username: str) -> None:
    record = USERS.get(username.strip().lower(), USERS["rocki"])
    st.session_state.auth_ok = True
    st.session_state.auth_user = username.strip().lower()
    st.session_state.auth_name = record["name"]
    st.session_state.auth_role = record["role"]


def _sign_out() -> None:
    for key in ["auth_ok", "auth_user", "auth_name", "auth_role"]:
        st.session_state[key] = False if key == "auth_ok" else None
    st.rerun()


def google_csv_url(gid: str) -> str:
    return f"https://docs.google.com/spreadsheets/d/{SPREADSHEET_ID}/export?format=csv&gid={gid}"


def has_service_account() -> bool:
    try:
        return bool(st.secrets.get("gcp_service_account")) and gspread is not None and Credentials is not None
    except Exception:
        return False


def read_private_sheet(gid: str) -> pd.DataFrame:
    scopes = ["https://www.googleapis.com/auth/spreadsheets.readonly"]
    creds = Credentials.from_service_account_info(dict(st.secrets["gcp_service_account"]), scopes=scopes)
    client = gspread.authorize(creds)
    workbook = client.open_by_key(SPREADSHEET_ID)
    worksheet = workbook.get_worksheet_by_id(int(gid))
    values = worksheet.get_all_values()
    if not values:
        return pd.DataFrame()
    headers = values[0]
    return pd.DataFrame(values[1:], columns=headers)


@st.cache_data(ttl=120, show_spinner=False)
def read_public_sheet(gid: str) -> pd.DataFrame:
    return pd.read_csv(google_csv_url(gid))


def first_line(value: Any, max_chars: int = 95) -> str:
    text = re.sub(r"\s+", " ", str(value or "")).strip()
    if not text:
        return ""
    line = text.split(".")[0].strip() or text
    return line[:max_chars].rstrip() + ("…" if len(line) > max_chars else "")


def extract_hashtags(text: Any) -> List[str]:
    return sorted(set(re.findall(r"#[A-Za-z0-9_]+", str(text or ""))))


def count_words(text: Any) -> int:
    return len(re.findall(r"\b\w+\b", str(text or "")))


def score_text(row: pd.Series) -> int:
    blob = " ".join(str(row.get(c, "")) for c in CHANNEL_COLUMNS)
    filled = sum(1 for c in CHANNEL_COLUMNS if str(row.get(c, "")).strip())
    keyword_bonus = sum(1 for k in ["client", "marketing", "student", "business", "school", "content", "brand", "confidence", "search", "offer", "beauty", "cosmetology"] if k in blob.lower())
    return min(10, 2 + min(4, filled // 2) + min(3, len(blob) // 1400) + min(1, keyword_bonus // 4))


def infer_primary_topic(row: pd.Series) -> str:
    for col in ["Trend", "Topic", "Title", "Research Strategy", "Blog", "Blog (AI Agent)", "IG", "Tiktok", "Linkedin", "Facebook"]:
        candidate = str(row.get(col, "")).strip()
        if candidate:
            return first_line(candidate)
    return "Google Sheets content row"


def infer_pillar(brand: str, topic: str) -> str:
    lower = topic.lower()
    if brand == "Social With Rocki":
        if "ai" in lower:
            return "AI Content Systems"
        if "search" in lower or "seo" in lower or "aeo" in lower:
            return "Search-First Social"
        if "client" in lower or "proof" in lower:
            return "Client Proof Content"
        if "newsletter" in lower or "community" in lower:
            return "Newsletter + Community"
        return "Beauty Business Marketing"
    if "state board" in lower or "exam" in lower:
        return "State Board Prep"
    if "student" in lower or "school" in lower or "kit" in lower:
        return "Beauty School Survival"
    if "client" in lower or "consult" in lower:
        return "Client Experience"
    if "business" in lower or "salon" in lower:
        return "Business Behind The Chair"
    return "Student Diary Series"


def normalize_sheet(df: pd.DataFrame, source: Dict[str, str]) -> pd.DataFrame:
    frame = df.copy()
    frame.columns = [str(c).strip() for c in frame.columns]

    for col in CHANNEL_COLUMNS:
        if col not in frame.columns:
            frame[col] = ""
    for col in source["expected_columns"]:
        if col not in frame.columns:
            frame[col] = ""

    if "Brand" not in frame.columns:
        frame["Brand"] = source["brand"]
    frame["Brand"] = frame["Brand"].fillna("").replace("", source["brand"])

    frame = frame.fillna("").astype(str)
    frame["Source Sheet"] = source["sheet_name"]
    frame["Source GID"] = source["gid"]
    frame["Source URL"] = google_csv_url(source["gid"])
    frame["Source Row"] = range(2, len(frame) + 2)
    frame["Trend"] = frame.apply(infer_primary_topic, axis=1)
    if "Pillar" not in frame.columns:
        frame["Pillar"] = ""
    frame["Pillar"] = frame.apply(lambda r: r.get("Pillar") or infer_pillar(str(r.get("Brand", source["brand"])), str(r.get("Trend", ""))), axis=1)
    frame["Hook"] = frame.apply(lambda r: first_line(r.get("IG") or r.get("Tiktok") or r.get("Linkedin") or r.get("Blog") or r.get("Research Strategy")), axis=1)
    frame["Search Intent"] = frame.apply(lambda r: f"Imported from {source['sheet_name']} Google Sheet", axis=1)
    frame["Target Audience"] = frame["Brand"].map(lambda b: BRAND_STRATEGY.get(b, BRAND_STRATEGY[source["brand"]])["audience"])
    frame["CTA"] = frame.apply(lambda r: "Copy, repurpose, schedule, or turn into a lead magnet.", axis=1)
    frame["Offer"] = frame["Brand"].map(lambda b: BRAND_STRATEGY.get(b, BRAND_STRATEGY[source["brand"]])["offers"][0])
    frame["Content Pieces"] = frame[CHANNEL_COLUMNS].apply(lambda r: int(r.astype(str).str.strip().ne("").sum()), axis=1)
    frame["Total Words"] = frame[CHANNEL_COLUMNS].apply(lambda r: sum(count_words(v) for v in r), axis=1)
    frame["Opportunity Score"] = frame.apply(score_text, axis=1)
    return frame


def load_google_sheets_only() -> Tuple[pd.DataFrame, pd.DataFrame]:
    frames = []
    status_rows = []
    using_private = has_service_account()

    for source in SHEET_SOURCES:
        try:
            if using_private:
                raw = read_private_sheet(source["gid"])
                mode = "Private service account"
            else:
                raw = read_public_sheet(source["gid"])
                mode = "Public CSV export"
            normalized = normalize_sheet(raw, source)
            frames.append(normalized)
            missing = [c for c in source["expected_columns"] if c not in raw.columns]
            status_rows.append({
                "Brand": source["brand"],
                "Sheet": source["sheet_name"],
                "GID": source["gid"],
                "Mode": mode,
                "Rows Pulled": len(raw),
                "Expected Columns": ", ".join(source["expected_columns"]),
                "Missing Expected Columns": ", ".join(missing) if missing else "None",
                "Status": "Connected",
                "Message": source["description"],
            })
        except Exception as exc:
            status_rows.append({
                "Brand": source["brand"],
                "Sheet": source["sheet_name"],
                "GID": source["gid"],
                "Mode": "Private service account" if using_private else "Public CSV export",
                "Rows Pulled": 0,
                "Expected Columns": ", ".join(source["expected_columns"]),
                "Missing Expected Columns": "Unknown",
                "Status": "Not connected",
                "Message": str(exc),
            })

    if frames:
        data = pd.concat(frames, ignore_index=True)
        data["Row"] = range(1, len(data) + 1)
    else:
        data = pd.DataFrame(columns=["Row", "Brand", "Source Sheet", "Source GID", "Source URL", "Source Row", "Trend", "Pillar", "Hook", "Search Intent", "Target Audience", "CTA", "Offer", "Content Pieces", "Total Words", "Opportunity Score"] + CHANNEL_COLUMNS)
    return data, pd.DataFrame(status_rows)


def build_long_df(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for _, row in df.iterrows():
        for column in CHANNEL_COLUMNS:
            content = str(row.get(column, "")).strip()
            if content:
                rows.append({
                    "Row": row.get("Row", ""),
                    "Brand": row.get("Brand", ""),
                    "Source Sheet": row.get("Source Sheet", ""),
                    "Source Row": row.get("Source Row", ""),
                    "Platform Key": column,
                    "Platform": DISPLAY_NAMES.get(column, column),
                    "Pillar": row.get("Pillar", ""),
                    "Trend": row.get("Trend", ""),
                    "Hook": row.get("Hook", ""),
                    "CTA": row.get("CTA", ""),
                    "Offer": row.get("Offer", ""),
                    "Content": content,
                    "Characters": len(content),
                    "Words": count_words(content),
                    "Hashtags": ", ".join(extract_hashtags(content)),
                    "Opportunity Score": int(row.get("Opportunity Score", 0) or 0),
                })
    return pd.DataFrame(rows)


def render_login_page() -> None:
    st.markdown("""
    <div class="login-shell"><div class="login-card">
    <div class="eyebrow">Private Google Sheets Content Studio</div>
    <div class="login-title">Rocki Content System</div>
    <div class="muted">This version reads from Google Sheets only: Sheet1 for Social With Rocki and rocki_cosmetology_7_day_demo_content for Cosmetology With Rocki. No local CSV fallback is used.</div>
    <div style="margin-top:16px"><span class="pill">Google Sheets Only</span><span class="pill green">Social With Rocki</span><span class="pill purple">Cosmetology With Rocki</span></div>
    </div></div>
    """, unsafe_allow_html=True)
    left, center, right = st.columns([1, 1.1, 1])
    with center:
        st.markdown("<div class='glass-card'>", unsafe_allow_html=True)
        with st.form("login_form"):
            username = st.text_input("Username", placeholder="rocki")
            password = st.text_input("Password", type="password", placeholder="rocki2026")
            submitted = st.form_submit_button("Open Content Studio", use_container_width=True)
        st.caption("Demo login: rocki / rocki2026")
        if submitted:
            if _check_login(username, password):
                _sign_in(username.strip())
                st.rerun()
            st.error("Invalid username or password.")
        st.markdown("</div>", unsafe_allow_html=True)


def render_hero(title: str, subtitle: str, badges: List[str]) -> None:
    badge_html = "".join(f"<span class='pill'>{escape(str(b))}</span>" for b in badges)
    st.markdown(f"""
    <div class="hero-card"><div class="eyebrow">Rocki Google Sheets Studio</div>
    <h1 style="margin:8px 0 12px">{escape(title)}</h1>
    <div class="muted" style="max-width:960px">{escape(subtitle)}</div>
    <div style="margin-top:14px">{badge_html}</div></div>
    """, unsafe_allow_html=True)


def render_sidebar(df: pd.DataFrame):
    with st.sidebar:
        st.markdown(f"""
        <div style='padding:.5rem 0 .25rem'><div class='eyebrow'>Signed in</div>
        <div style='font-family:"Playfair Display",serif;font-size:1.55rem;color:#27151f;margin-top:4px;font-weight:900'>{escape(str(st.session_state.auth_name or 'Member'))}</div>
        <div class='muted'>{escape(str(st.session_state.auth_role or 'User'))}</div></div>
        """, unsafe_allow_html=True)
        page = st.radio("Pages", ["Dashboard", "Google Sheets Source", "Social With Rocki", "Cosmetology With Rocki", "Trend Finder", "Social Content Library", "Content Calendar"], label_visibility="collapsed")
        st.markdown("---")
        brand_options = sorted(df["Brand"].dropna().unique()) if not df.empty else [s["brand"] for s in SHEET_SOURCES]
        brands = st.multiselect("Brands", brand_options, default=brand_options)
        platforms = st.multiselect("Platforms", CHANNEL_COLUMNS, default=CHANNEL_COLUMNS, format_func=lambda v: f"{PLATFORM_ICONS.get(v, '•')} {DISPLAY_NAMES.get(v, v)}")
        query = st.text_input("Search Google Sheets content", placeholder="AI, client, student, kit, state board...")
        st.markdown("---")
        st.caption("Data source: Google Sheets only")
        if st.button("Refresh Google Sheets", use_container_width=True):
            st.cache_data.clear()
            st.rerun()
        if st.button("Sign Out", use_container_width=True):
            _sign_out()
    return page, brands, platforms, query


def filtered_rows(df: pd.DataFrame, brands: List[str], query: str) -> pd.DataFrame:
    active = df[df["Brand"].isin(brands)].copy() if brands else df.copy()
    if query.strip() and not active.empty:
        cols = ["Brand", "Source Sheet", "Pillar", "Trend", "Hook", "CTA", "Offer"] + CHANNEL_COLUMNS
        available = [c for c in cols if c in active.columns]
        mask = active[available].apply(lambda c: c.astype(str).str.contains(query.strip(), case=False, na=False))
        active = active[mask.any(axis=1)]
    return active.reset_index(drop=True)


def render_metrics(df: pd.DataFrame, long_df: pd.DataFrame) -> None:
    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric("Sheet Rows", len(df))
    c2.metric("Content Assets", len(long_df))
    c3.metric("Brands", df["Brand"].nunique() if not df.empty else 0)
    c4.metric("Avg Score", round(float(df["Opportunity Score"].mean()), 1) if not df.empty else 0)
    c5.metric("Total Words", f"{int(long_df['Words'].sum()):,}" if not long_df.empty else "0")


def render_source_status(status_df: pd.DataFrame) -> None:
    render_hero("Google Sheets Source", "This dashboard reads only from the two Google Sheets append targets you provided. Add or generate content through n8n, then refresh this page to pull the latest rows.", [SPREADSHEET_ID, "No local CSV fallback", "Read-only dashboard"])
    st.markdown("### Connected Sheet Tabs")
    for _, row in status_df.iterrows():
        ok = row["Status"] == "Connected"
        status_class = "source-ok" if ok else "source-bad"
        st.markdown(f"""
        <div class='content-card'>
        <div class='eyebrow'>{safe_html(row['Brand'])}</div>
        <div class='content-title'>{safe_html(row['Sheet'])} • gid {safe_html(row['GID'])}</div>
        <div class='trend-copy'><b>Status:</b> <span class='{status_class}'>{safe_html(row['Status'])}</span><br><b>Mode:</b> {safe_html(row['Mode'])}<br><b>Rows pulled:</b> {safe_html(row['Rows Pulled'])}<br><b>Expected columns:</b> {safe_html(row['Expected Columns'])}<br><b>Missing columns:</b> {safe_html(row['Missing Expected Columns'])}<br><b>Message:</b> {safe_html(row['Message'])}</div>
        <span class='pill'>Google Sheets only</span><span class='pill green'>No demo CSV</span></div>
        """, unsafe_allow_html=True)
    st.markdown("### Exact Sheet Export URLs")
    url_table = pd.DataFrame([{"Brand": s["brand"], "Sheet": s["sheet_name"], "GID": s["gid"], "CSV Export URL": google_csv_url(s["gid"])} for s in SHEET_SOURCES])
    st.dataframe(url_table, use_container_width=True, hide_index=True)
    st.info("If a tab shows Not connected, either publish the sheet/tab so CSV export is readable, or add a Google service account to Streamlit secrets under gcp_service_account and share the spreadsheet with that service account email.")


def render_dashboard(df: pd.DataFrame, status_df: pd.DataFrame, brands: List[str], platforms: List[str], query: str) -> None:
    active = filtered_rows(df, brands, query)
    long_df = build_long_df(active)
    if platforms and not long_df.empty:
        long_df = long_df[long_df["Platform Key"].isin(platforms)]
    render_hero("Google Sheets Command Center", "A read-only Streamlit dashboard connected directly to your two Google Sheets append tabs: Social With Rocki content from Sheet1 and Cosmetology With Rocki content from rocki_cosmetology_7_day_demo_content.", ["Google Sheets only", "n8n-ready", f"Updated {datetime.now().strftime('%b %d, %Y %I:%M %p')}"])
    render_metrics(active, long_df)
    left, right = st.columns([1.35, .95], gap="large")
    with left:
        st.markdown("### Content By Brand")
        if not active.empty:
            brand_chart = active.groupby("Brand")[["Content Pieces", "Total Words", "Opportunity Score"]].mean(numeric_only=True)
            st.bar_chart(brand_chart)
        st.markdown("### Latest Google Sheet Rows")
        cols = ["Row", "Brand", "Source Sheet", "Source Row", "Pillar", "Trend", "Content Pieces", "Total Words", "Opportunity Score"]
        st.dataframe(active[cols] if not active.empty else active, use_container_width=True, hide_index=True, column_config={"Trend": st.column_config.TextColumn(width="large"), "Opportunity Score": st.column_config.ProgressColumn(min_value=0, max_value=10)})
    with right:
        st.markdown("### Source Health")
        for _, source in status_df.iterrows():
            status = "✅ Connected" if source["Status"] == "Connected" else "⚠️ Not connected"
            st.markdown(f"""
            <div class='mini-card'><div class='eyebrow'>{safe_html(source['Brand'])}</div>
            <div class='content-title'>{status}</div><div class='muted'>{safe_html(source['Sheet'])}: {safe_html(source['Rows Pulled'])} rows pulled.</div></div>
            """, unsafe_allow_html=True)
        st.markdown("### Posting Direction")
        st.markdown("""
        <div class='glass-card'><ul class='check-list'>
        <li>Generate content in n8n.</li>
        <li>Append rows to one of the two configured Google Sheet tabs.</li>
        <li>Refresh this Streamlit dashboard.</li>
        <li>Copy, filter, export, and schedule from the live Sheet data.</li>
        </ul></div>
        """, unsafe_allow_html=True)


def render_brand_page(df: pd.DataFrame, brand: str) -> None:
    info = BRAND_STRATEGY[brand]
    active = df[df["Brand"] == brand].copy()
    long_df = build_long_df(active)
    render_hero(brand, info["tagline"], ["Google Sheet powered", f"{len(active)} sheet rows", f"{len(long_df)} platform assets"])
    st.markdown(f"""
    <div class='glass-card'><div class='brand-band'></div><div class='content-title'>Brand Promise</div>
    <div class='content-copy'>{safe_html(info['promise'])}</div>
    <div style='margin-top:12px'><span class='pill green'>{safe_html(info['audience'])}</span></div></div>
    """, unsafe_allow_html=True)
    c1, c2 = st.columns([1, 1], gap="large")
    with c1:
        st.markdown("### Pillars")
        html = "<div class='card-grid'>"
        for pillar in info["pillars"]:
            count = int((active["Pillar"] == pillar).sum()) if not active.empty else 0
            html += f"<div class='mini-card'><div class='big-number'>{count}</div><div class='content-title'>{escape(pillar)}</div><div class='muted'>Rows matched from Google Sheets.</div></div>"
        html += "</div>"
        st.markdown(html, unsafe_allow_html=True)
    with c2:
        st.markdown("### Offer Ladder")
        st.markdown("<div class='glass-card'>" + "".join(f"<span class='pill purple'>{escape(o)}</span>" for o in info["offers"]) + "</div>", unsafe_allow_html=True)
        st.markdown("### Sheet Rows")
        if active.empty:
            st.info("No Google Sheet rows found for this brand yet.")
        else:
            st.dataframe(active[["Source Sheet", "Source Row", "Trend", "Content Pieces", "Total Words", "Opportunity Score"]], use_container_width=True, hide_index=True)
    st.markdown("### Copy-Ready Brand Cards")
    if long_df.empty:
        st.info("No post content found in this Google Sheet tab yet.")
    for idx, row in long_df.reset_index(drop=True).iterrows():
        icon = PLATFORM_ICONS.get(str(row.get("Platform Key", "")), "✨")
        st.markdown(f"""
        <div class='content-card'><div class='eyebrow'>{safe_html(row['Source Sheet'])} • Row {safe_html(row['Source Row'])} • {safe_html(row['Pillar'])}</div>
        <div class='content-title'>{icon} {safe_html(row['Platform'])}: {safe_html(row['Trend'])}</div>
        <div class='trend-copy'><b>Hook:</b> {safe_html(row['Hook'])}<br><b>CTA:</b> {safe_html(row['CTA'])}<br><b>Offer:</b> {safe_html(row['Offer'])}</div>
        <span class='pill purple'>{safe_html(row['Characters'])} chars</span><span class='pill green'>{safe_html(row['Words'])} words</span><span class='pill'>Score {safe_html(row['Opportunity Score'])}/10</span></div>
        """, unsafe_allow_html=True)
        st.text_area("Copy content", value=str(row["Content"]), height=240 if int(row["Characters"]) > 900 else 170, key=f"brand_{brand}_{idx}", label_visibility="collapsed")


def render_trend_finder(df: pd.DataFrame) -> None:
    render_hero("Trend Finder", "This page does not invent trends locally. It surfaces topics, hooks, and content opportunities already present in the two connected Google Sheet tabs.", ["Sheet-fed", "Searchable", "Exportable"])
    if df.empty:
        st.warning("No Google Sheet rows are available yet.")
        return
    b1, b2, b3 = st.columns([1, 1, 1])
    with b1:
        brand_filter = st.multiselect("Brand", sorted(df["Brand"].unique()), default=sorted(df["Brand"].unique()))
    with b2:
        pillar_filter = st.multiselect("Pillar", sorted(df["Pillar"].unique()), default=sorted(df["Pillar"].unique()))
    with b3:
        min_score = st.slider("Minimum Score", 0, 10, 0)
    active = df[df["Brand"].isin(brand_filter) & df["Pillar"].isin(pillar_filter) & (df["Opportunity Score"].astype(int) >= min_score)].copy()
    st.download_button("Download Google Sheet Trend Board CSV", data=active.to_csv(index=False).encode("utf-8"), file_name="rocki_gsheets_trend_board.csv", mime="text/csv", use_container_width=True)
    for _, row in active.sort_values(["Brand", "Opportunity Score"], ascending=[True, False]).iterrows():
        st.markdown(f"""
        <div class='content-card'><div class='eyebrow'>{safe_html(row['Brand'])} • {safe_html(row['Source Sheet'])} row {safe_html(row['Source Row'])}</div>
        <div class='content-title'>{safe_html(row['Trend'])}</div>
        <div class='trend-copy'><b>Pillar:</b> {safe_html(row['Pillar'])}<br><b>Hook:</b> {safe_html(row['Hook'])}<br><b>Search intent:</b> {safe_html(row['Search Intent'])}<br><b>Audience:</b> {safe_html(row['Target Audience'])}</div>
        <span class='pill purple'>Offer: {safe_html(row['Offer'])}</span><span class='pill'>Score {safe_html(row['Opportunity Score'])}/10</span><span class='pill green'>{safe_html(row['Content Pieces'])} assets</span></div>
        """, unsafe_allow_html=True)


def render_social_library(df: pd.DataFrame, brands: List[str], platforms: List[str], query: str) -> None:
    active_rows = filtered_rows(df, brands, query)
    long_df = build_long_df(active_rows)
    if platforms and not long_df.empty:
        long_df = long_df[long_df["Platform Key"].isin(platforms)]
    render_hero("Social Content Library", "Copy-ready content pulled directly from the two Google Sheet tabs. Add or edit content in Google Sheets, then refresh this dashboard.", ["Google Sheets only", "No session posts", "No CSV fallback"])
    if long_df.empty:
        st.info("No content matches the current filters or the Google Sheets tabs are empty.")
        return
    left, mid, right = st.columns([1, 1, 1])
    with left:
        pfilter = st.multiselect("Library Platform", sorted(long_df["Platform"].unique()), default=sorted(long_df["Platform"].unique()))
    with mid:
        brand_filter = st.multiselect("Library Brand", sorted(long_df["Brand"].unique()), default=sorted(long_df["Brand"].unique()))
    with right:
        min_chars = st.slider("Minimum Characters", 0, int(max(1000, long_df["Characters"].max())), 0)
    active = long_df[long_df["Platform"].isin(pfilter) & long_df["Brand"].isin(brand_filter) & (long_df["Characters"] >= min_chars)].copy()
    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Active Assets", len(active))
    m2.metric("Brands", active["Brand"].nunique() if not active.empty else 0)
    m3.metric("Platforms", active["Platform"].nunique() if not active.empty else 0)
    m4.metric("Avg Words", int(active["Words"].mean()) if not active.empty else 0)
    export_cols = ["Brand", "Source Sheet", "Source Row", "Platform", "Pillar", "Trend", "Hook", "CTA", "Offer", "Content", "Characters", "Words", "Hashtags", "Opportunity Score"]
    st.download_button("Download Active Google Sheets Content CSV", data=active[export_cols].to_csv(index=False).encode("utf-8"), file_name="rocki_google_sheets_social_content.csv", mime="text/csv", use_container_width=True)
    st.markdown("### Add New Posts")
    st.info("This version is Google Sheets only. To add a post, append a row through your n8n Google Sheets nodes or edit the Google Sheet directly, then click Refresh Google Sheets.")
    st.markdown("### Copy-Ready Cards")
    for idx, row in active.reset_index(drop=True).iterrows():
        icon = PLATFORM_ICONS.get(str(row.get("Platform Key", "")), "✨")
        st.markdown(f"""
        <div class='content-card'><div class='eyebrow'>{safe_html(row['Brand'])} • {safe_html(row['Source Sheet'])} row {safe_html(row['Source Row'])} • {safe_html(row['Pillar'])}</div>
        <div class='content-title'>{icon} {safe_html(row['Platform'])}: {safe_html(row['Trend'])}</div>
        <div class='trend-copy'><b>Hook:</b> {safe_html(row['Hook'])}<br><b>CTA:</b> {safe_html(row['CTA'])}<br><b>Offer:</b> {safe_html(row['Offer'])}</div>
        <span class='pill purple'>{safe_html(row['Characters'])} chars</span><span class='pill green'>{safe_html(row['Words'])} words</span><span class='pill'>Score {safe_html(row['Opportunity Score'])}/10</span><span class='pill gold'>{safe_html(row['Hashtags'])}</span></div>
        """, unsafe_allow_html=True)
        st.text_area("Copy content", value=str(row["Content"]), height=250 if int(row["Characters"]) > 900 else 170, key=f"copy_{row['Row']}_{row['Platform Key']}_{idx}", label_visibility="collapsed")
    st.markdown("### Planning Table")
    st.dataframe(active[export_cols], use_container_width=True, hide_index=True, column_config={"Trend": st.column_config.TextColumn(width="large"), "Content": st.column_config.TextColumn(width="large"), "Opportunity Score": st.column_config.ProgressColumn(min_value=0, max_value=10)})


def render_calendar(df: pd.DataFrame) -> None:
    render_hero("Content Calendar", "A publishing view built only from Google Sheet rows. The source row stays visible so you can trace every calendar idea back to the exact Sheet tab.", ["Sheet rows", "Traceable", "Exportable"])
    if df.empty:
        st.info("No Google Sheet rows available for calendar planning yet.")
        return
    records = []
    for _, row in df.iterrows():
        records.append({
            "Brand": row.get("Brand", ""),
            "Source Sheet": row.get("Source Sheet", ""),
            "Source Row": row.get("Source Row", ""),
            "Primary Platform": "TikTok + IG" if row.get("Brand") == "Cosmetology With Rocki" else "LinkedIn + IG",
            "Secondary Platforms": "Pinterest, Facebook, Newsletter, Blog",
            "Trend / Topic": row.get("Trend", ""),
            "Repurpose Plan": "Turn the strongest post into a short video, carousel, email, and Pinterest pin.",
            "CTA": row.get("CTA", ""),
            "Offer": row.get("Offer", ""),
        })
    cal = pd.DataFrame(records)
    st.dataframe(cal, use_container_width=True, hide_index=True, column_config={"Trend / Topic": st.column_config.TextColumn(width="large"), "Repurpose Plan": st.column_config.TextColumn(width="medium")})
    st.download_button("Download Google Sheets Content Calendar CSV", data=cal.to_csv(index=False).encode("utf-8"), file_name="rocki_google_sheets_content_calendar.csv", mime="text/csv", use_container_width=True)


def render_app() -> None:
    df, status_df = load_google_sheets_only()
    page, brands, platforms, query = render_sidebar(df)
    if page == "Dashboard":
        render_dashboard(df, status_df, brands, platforms, query)
    elif page == "Google Sheets Source":
        render_source_status(status_df)
    elif page == "Social With Rocki":
        render_brand_page(df, "Social With Rocki")
    elif page == "Cosmetology With Rocki":
        render_brand_page(df, "Cosmetology With Rocki")
    elif page == "Trend Finder":
        render_trend_finder(df)
    elif page == "Social Content Library":
        render_social_library(df, brands, platforms, query)
    else:
        render_calendar(filtered_rows(df, brands, query))


_init_state()
if not st.session_state.auth_ok:
    render_login_page()
else:
    render_app()
